### ISSUE TITLE
Unable to catch exception thrown in plugin

### ISSUE THREAD

**Issue by fddOs** [pf4j/pf4j#211]
I throw an exception in the plug-in, and then catch the exception in the application through the following code, but without success, what should I do to catch the exception thrown by the plug-in

```java
try {
    jobPlugins.get(0).execute();
} catch (Exception e) {
    e.printStackTrace();
}
```

@decebals

**Comment by decebals** [comment]
I don't understand your code.
For exemple:
```java
jobPlugins.get(0).execute();
```

Can you give us more details about what type is JobPlugin? How you retrieve the list with job plugins, are they Extensions and you use pluginManager.getExtension(<extensionPoint>)?

**Comment by fddOs** [comment]
ok
```
public interface JobPlugin extends ExtensionPoint {
	void execute(String jobName) throw Exception;
}
```


```
PluginManager pluginManager = new SpringPluginManager();
pluginManager.loadPlugin(pluginPath);
pluginManager.startPlugins();
List<JobPlugin> jobPlugins = pluginManager.getExtensions(JobPlugin.class);
try {
	jobPlugins.get(0).execute(params)
} catch (Exception e) {
        e.printStackTrace();
}
```

**Comment by decebals** [comment]
And you say that you throw an exception in `execute` method but you don't see the stack trace in the console.
PF4J doesn't something special. Can you put a breakpoint on `jobPlugins.get(0).execute(params)` and run in debug mode from your IDE (Eclipse, ...) to see if your assumption that an exception is thrown is correct?

**Comment by fddOs** [comment]
I found the reason. It was a stupid mistake. I forgot to repackage the plug-in project after updating the code, so I can't catch exceptions during debugging. I'm sorry. o(╥﹏╥)o

**Comment by decebals** [comment]
No problem. Please close the issue.

**Comment by meydominic** [comment]
I would like to reopen this issue because I'm not able to catch exceptions which are thrown in plugins.

For example if I want to register extensions and there is an exception.

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/xyz/tool/plugins/extensions/EventExtension
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at org.pf4j.PluginClassLoader.loadClass(PluginClassLoader.java:109)
	at org.pf4j.AbstractExtensionFinder.find(AbstractExtensionFinder.java:196)
	at org.pf4j.DefaultExtensionFinder.find(DefaultExtensionFinder.java:65)
	at org.pf4j.AbstractPluginManager.getExtensions(AbstractPluginManager.java:595)
	at com.xyz.tool.plugins.core.manager.PluginExtensionManager.registerExtensions(PluginExtensionManager.java:88)
```
Even if I put .getExtensions() in try/catch it won't be caught. The exception above is only an example which I built.
