### ISSUE TITLE
How/When are extension classes instantiated?

### ISSUE THREAD

**Issue by jgomer2001** [pf4j/pf4j#232]
Hi,
I'm trying to understand under which circumstances extensions classes are instantiated.

Say, we have a simple setup as the one shown in the readme of this repo, like this:

```
public interface Greeting extends ExtensionPoint { ...
```

```
public class WelcomePlugin extends Plugin {
...
	@Extension
	public static class WelcomeGreeting implements Greeting {

		public WelcomeGreeting() {
			System.out.println("Hello");
		}
		
		...
	}
}
```

```
public static void main(String[] args) {
    ...
    
    pluginManager.getExtensions(Greeting.class);
    ...
}

```

This will basically print "Hello" once. 

If I add `pluginManager.getExtensions(Greeting.class)` once more, "Hello" will be printed twice.

Calling `getExtensions` multiple times makes sense for instance, when you want to add plugins at runtime (ie a new plugin implementing the Greeting extension point), so I think it feels more natural the `WelcomeGreeting` constructor being called just once. If more extensions are added afterwards, their corresponding constructors would be called upon a next `getExtensions`.

Any opinion or insight around this topic is valuable.

**Comment by decebals** [comment]
> If I add pluginManager.getExtensions(Greeting.class) once more, "Hello" will be printed twice.

If you call `pluginManager.getExtensions(Greeting.class)` two time, "Hello" will be printed twice. A new instance of extension is created on each pluginManager.getExtensions() call.

If you want to return the same extension instance (singleton) for each `pluginManager.getExtensions()` call, you need to override `AbstractPluginManager.createExtensionFactory` like [here](https://github.com/pf4j/pf4j-spring/blob/master/pf4j-spring/src/main/java/org/pf4j/spring/SpringPluginManager.java#L43).

In the end, we can create a new class `SingletonExtensionFactory` similar with [SingletonSpringExtensionFactory](https://github.com/pf4j/pf4j-spring/blob/master/pf4j-spring/src/main/java/org/pf4j/spring/SingletonSpringExtensionFactory.java) if it's useful.

**Comment by decebals** [comment]
I added a new [section](https://pf4j.org/doc/extension-instantiation.html) in documentation.
I added `SingletonExtensionFactory` that is included in current `SNAPSHOT`.

**Comment by jgomer2001** [comment]
Hi there,
Two observations:

- In the page you added, just before the code snippet at the very bottom, you are pointing to the same page (extension-instantiation.html), I think the right link is [this](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/SingletonExtensionFactory.java).

- I followed the steps (extending defaultPluginManager and creating my own factory) but was getting NPE:

```
java.lang.NullPointerException: null
at org.pf4j.ExtensionWrapper.getExtension(ExtensionWrapper.java:37) ~[pf4j-2.2.0.jar:2.2.0]
	at org.pf4j.AbstractPluginManager.getExtensions(AbstractPluginManager.java:561) ~[pf4j-2.2.0.jar:2.2.0]
```

After some code diving (this is 2.2.0), I found `AbstractExtensionFinder#createExtensionWrapper` is calling `pluginManager.getExtensionFactory()` so I also override that method in my `pluginManger`. That did the trick.

**Comment by decebals** [comment]
I fixed the broken link, thanks!

> I followed the steps (extending defaultPluginManager and creating my own factory) but was getting NPE

I tested and it works:
![image](https://user-images.githubusercontent.com/1248311/43014302-654e8844-8c54-11e8-938c-f2e3c22d5bfe.png)
