### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by zhanghuidouble** [pf4j/pf4j#259]
hi,
 I use gradle_demo build for my plugins,my pluginDir like this:
-- Plugin1.zip
   - classes
      - com.test.plugin
         - PluginComponent_1.class
   - lib
     - *.jar
      - *.jar

-- Plugin2.zip
   - classes
      - com.test.plugin
         - PluginComponent_2.class
   - lib
     - *.jar
      - *.jar

but it run with error:
java.lang.ClassNotFoundException: com.test.plugin.PluginComponent_1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.pf4j.PluginClassLoader.loadClass(PluginClassLoader.java:126)
	at org.pf4j.DefaultPluginFactory.create(DefaultPluginFactory.java:46)
	at org.pf4j.PluginWrapper.getPlugin(PluginWrapper.java:78)
	at org.pf4j.AbstractPluginManager.startPlugins(AbstractPluginManager.java:326)

**Comment by zhanghuidouble** [comment]
can I run the Main method of demo_gradle APP Boot class? I run the Method,also error:

objc[2760]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin/java (0x10c70e4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10c7e14e0). One of the two will be used. Which one is undefined.
Connected to the target VM, address: '127.0.0.1:49911', transport: 'socket'
[main] INFO org.pf4j.demo.Boot - ########################################
[main] INFO org.pf4j.demo.Boot -                PF4J-DEMO                
[main] INFO org.pf4j.demo.Boot - ########################################
[main] INFO org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
[main] INFO org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
[main] INFO org.pf4j.DefaultPluginManager - PF4J version 2.0.0 in 'deployment' mode
[main] ERROR org.pf4j.AbstractPluginManager - Field 'id' cannot be empty
org.pf4j.PluginException: Field 'id' cannot be empty
	at org.pf4j.AbstractPluginManager.validatePluginDescriptor(AbstractPluginManager.java:853)
	at org.pf4j.AbstractPluginManager.loadPluginFromPath(AbstractPluginManager.java:787)
	at org.pf4j.DefaultPluginManager.loadPluginFromPath(DefaultPluginManager.java:137)
	at org.pf4j.AbstractPluginManager.loadPlugins(AbstractPluginManager.java:230)
	at org.pf4j.demo.Boot.main(Boot.java:56)
[main] INFO org.pf4j.AbstractPluginManager - Plugin 'welcome-plugin@0.0.1' resolved
[main] INFO org.pf4j.AbstractPluginManager - Plugin 'hello-plugin@0.0.1' resolved
[main] INFO org.pf4j.AbstractPluginManager - Start plugin 'welcome-plugin@0.0.1'
[main] ERROR org.pf4j.DefaultExtensionFactory - org.pf4j.demo.welcome.WelcomePlugin
java.lang.ClassNotFoundException: org.pf4j.demo.welcome.WelcomePlugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.pf4j.PluginClassLoader.loadClass(PluginClassLoader.java:115)
	at org.pf4j.DefaultPluginFactory.create(DefaultPluginFactory.java:46)
	at org.pf4j.PluginWrapper.getPlugin(PluginWrapper.java:78)
	at org.pf4j.AbstractPluginManager.startPlugins(AbstractPluginManager.java:329)
	at org.pf4j.demo.Boot.main(Boot.java:62)
Exception in thread "main" java.lang.NullPointerException
	at org.pf4j.AbstractPluginManager.startPlugins(AbstractPluginManager.java:329)
	at org.pf4j.demo.Boot.main(Boot.java:62)

**Comment by zhanghuidouble** [comment]
run with jar:
demo_gradle git:(master) ✗ java -jar -Dpf4j.pluginsDir=build/plugins app/build/libs/app-plugin-demo-uberjar.jar


[main] INFO org.pf4j.demo.Boot - ########################################
[main] INFO org.pf4j.demo.Boot -                PF4J-DEMO                
[main] INFO org.pf4j.demo.Boot - ########################################
[main] INFO org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
[main] INFO org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
[main] INFO org.pf4j.DefaultPluginManager - PF4J version 0.0.0 in 'deployment' mode
[main] INFO org.pf4j.AbstractPluginManager - Plugin 'welcome-plugin@0.0.1' resolved
[main] INFO org.pf4j.AbstractPluginManager - Plugin 'hello-plugin@0.0.1' resolved
[main] INFO org.pf4j.AbstractPluginManager - Start plugin 'welcome-plugin@0.0.1'
[main] INFO org.pf4j.demo.welcome.WelcomePlugin - WelcomePlugin.start()
[main] INFO org.pf4j.demo.welcome.WelcomePlugin - WELCOMEPLUGIN
[main] INFO org.pf4j.AbstractPluginManager - Start plugin 'hello-plugin@0.0.1'
[main] INFO org.pf4j.demo.hello.HelloPlugin - HelloPlugin.start()
[main] INFO org.pf4j.demo.Boot - Plugindirectory: 
[main] INFO org.pf4j.demo.Boot -        build/plugins

Exception in thread "main" java.lang.NoClassDefFoundError: org/pf4j/demo/api/Greeting
        at org.pf4j.demo.Boot.main(Boot.java:68)
Caused by: java.lang.ClassNotFoundException: org.pf4j.demo.api.Greeting
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more

**Comment by zhanghuidouble** [comment]
@decebals  can the gradle_demo run normally? I need your help,thanks!

**Comment by zhanghuidouble** [comment]
sorry may be gradle build error,it works for nothing changed.
