### ISSUE TITLE
startPlugin error:class not found

### ISSUE THREAD

**Issue by zhanghuidouble** [pf4j/pf4j#260]
when I use pluginManager.loadPlugins();
                    pluginManager.startPlugins();   in my class but not MainMethod,it run with errors:

```json
java.lang.ClassNotFoundException: com.test.adapters.plugin.PluginComponent
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.pf4j.PluginClassLoader.loadClass(PluginClassLoader.java:126)
	at org.pf4j.DefaultPluginFactory.create(DefaultPluginFactory.java:46)
	at org.pf4j.PluginWrapper.getPlugin(PluginWrapper.java:78)
	at org.pf4j.AbstractPluginManager.startPlugins(AbstractPluginManager.java:326)
```

**Comment by decebals** [comment]
Can you give us more details?
For stack trace I suppose that `com.test.adapters.plugin.PluginComponent` is the plugin class defined in plugin descriptor (MANIFEST.MF or plugin.properties). Is this class exists (correct spell, ...)?

**Comment by decebals** [comment]
Any news?

**Comment by decebals** [comment]
I will close this issue because of the lack of feedback. Please open it if you want to continue the discussion.

**Comment by svarma11** [comment]
Hi I am using third party library in the plugin using the maven which is not the part of main appliication 
whenever pluging gets loaded it try to use 3rd party library its throwing java.lang.NoClassDefFoundError

**Comment by decebals** [comment]
A stack trace or something similar is welcome
