### ISSUE TITLE
Can't delete/remove unloaded plugin

### ISSUE THREAD

**Issue by meydominic** [pf4j/pf4j#309]
Hi,
I found a little issue. I don't know if it's only on my end.

How to reproduce it:
- Start the application and install a plugin
- After installing it, deactivate it
- Restart your application -> The plugin won't be started by application
- Try to delete (`pluginManager.deletePlugin(plugin.getPluginId());`) the plugin.
- A ClassNotFoundException is thrown

![image](https://user-images.githubusercontent.com/2743382/55793797-01b15700-5ac4-11e9-9ba4-41f30c32178d.png)

If I activate the plugin and then tries to delete/remove it there is no issue. The same if I activate the plugin and then deactivate it again and then tries to delete/remove it.

The problem occurs only if I try to delete/remove a plugin which was not loaded/started by application with application-start.

Tested on macOS 10.14.4 with Java 1.8.0_202

**Comment by decebals** [comment]
Please try on a more short workflow:
- with your application stopped, disable the plugin (put the pluginId in the `disabled.txt` file - see https://pf4j.org/doc/disable-plugins.html)
- start your application
- try to delete (`pluginManager.deletePlugin(plugin.getPluginId())`) the plugin

Can you reproduce the issue on above workflow?

**Comment by decebals** [comment]
Can you paste (in a comment_ the full text of the stacktrace on `ClassNotFoundException`?

**Comment by meydominic** [comment]
With your mentioned workflow the result is the same

```
[ERROR] 2019-04-10 14:25:53.300 [qtp2053628870-26] P - []: java.lang.NullPointerException
	at org.pf4j.AbstractPluginManager.deletePlugin(AbstractPluginManager.java:307)
	at com.xyz.tool.plugins.core.manager.PluginInstallationManager.uninstallPlugin(PluginInstallationManager.java:122)
	at com.xyz.tool.servlets.PluginServlet.uninstallPlugin(PluginServlet.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:679)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at com.xyz.tool.server.rest.filter.AccessTokenFilter.handle(AccessTokenFilter.java:55)
	at com.xyz.tool.server.rest.filter.AccessTokenFilter.doFilter(AccessTokenFilter.java:40)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at com.xyz.tool.server.rest.filter.CrossOriginFilter.handle(CrossOriginFilter.java:43)
	at com.xyz.tool.server.rest.filter.CrossOriginFilter.doFilter(CrossOriginFilter.java:22)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at com.xyz.tool.server.rest.filter.MinorVersionRequestFilter.handle(MinorVersionRequestFilter.java:48)
	at com.xyz.tool.server.rest.filter.MinorVersionRequestFilter.doFilter(MinorVersionRequestFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

[INFO ] 2019-04-10 14:25:53.302 [qtp2053628870-26] P - []: Error occurred while uninstall helloworld

```

and
```
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	  at org.pf4j.PluginClassLoader.loadClass(PluginClassLoader.java:109)
	  at org.pf4j.DefaultPluginFactory.create(DefaultPluginFactory.java:46)
	  at org.pf4j.PluginWrapper.getPlugin(PluginWrapper.java:78)
	  at org.pf4j.AbstractPluginManager.deletePlugin(AbstractPluginManager.java:307)
	  at com.xyz.tool.plugins.core.manager.PluginInstallationManager.uninstallPlugin(PluginInstallationManager.java:122)
	  at com.xyz.tool.servlets.PluginServlet.uninstallPlugin(PluginServlet.java:66)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	  at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$$Lambda$188.486715174.invoke(Unknown Source:-1)
	  at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	  at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	  at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	  at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	  at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	  at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	  at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	  at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	  at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	  at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	  at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	  at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	  at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	  at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	  at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	  at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:679)
	  at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
	  at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	  at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)
	  at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)
	  at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	  at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
	  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	  at com.xyz.tool.server.rest.filter.AccessTokenFilter.handle(AccessTokenFilter.java:55)
	  at com.xyz.tool.server.rest.filter.AccessTokenFilter.doFilter(AccessTokenFilter.java:40)
	  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	  at com.xyz.tool.server.rest.filter.CrossOriginFilter.handle(CrossOriginFilter.java:43)
	  at com.xyz.tool.server.rest.filter.CrossOriginFilter.doFilter(CrossOriginFilter.java:22)
	  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	  at com.xyz.tool.server.rest.filter.MinorVersionRequestFilter.handle(MinorVersionRequestFilter.java:48)
	  at com.xyz.tool.server.rest.filter.MinorVersionRequestFilter.doFilter(MinorVersionRequestFilter.java:30)
	  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	  at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	  at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	  at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	  at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	  at org.eclipse.jetty.server.Server.handle(Server.java:502)
	  at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	  at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	  at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	  at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	  at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427)
	  at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321)
	  at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	  at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	  at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	  at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	  at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	  at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	  at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	  at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	  at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	  at java.lang.Thread.run(Thread.java:748)
```

**Comment by decebals** [comment]
The problem is related to https://github.com/pf4j/pf4j/issues/242 (Add delete hook method in Plugin). I will take a look and I will come with a solution asap.

**Comment by decebals** [comment]
I'll explain where the problem is, maybe together we can find a solution. I didn't find a clean solution until now, but maybe I'm blind.

So, in [AbstractPluginManager.deletePlugin](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/AbstractPluginManager.java#L292) below steps are executed:
- stop the plugin (if the plugin was started)
- unload the plugin
   - remove plugin from the plugins list
   - remove plugin from the resolved plugins list
   - close the plugin `ClassLoader` (`PluginClassLoader`) => no class can be loaded after this operation
   - remove the plugin class loader form the list with plugins class loaders
- notify the plugin that it will be deleted ([Plugin.delete](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/Plugin.java#L77))
- delete plugin from repository (file system)

The code  snippet from `deletePlugin` method that notifies the plugin that it is going to be deleted is:
```java
try {
    pluginWrapper.getPlugin().delete();
} catch (PluginException e) {
    log.error(e.getMessage(), e);
    return false;
}
```

The `PluginWrapper.getPlugin` method looks like:
```java
public Plugin getPlugin() {
    if (plugin == null) {
        plugin = pluginFactory.create(this);
    }

    return plugin;
}
```

So, it's clear from above workflow of `deletePlugin` method, that we try to create a plugin instance (`plugin == null`) after the class loader was closed (the result is `ClassNotFoundException`). 

Here is the dilemma, we want to notify a plugin (instance) that was never created/instantiated (because the plugin was disabled from beginning).

**Comment by pinhead84** [comment]
> Here is the dilemma, we want to notify a plugin (instance) that was never created/instantiated (because the plugin was disabled from beginning).

Maybe I'm missing something. But why not just ignore the notification of the plugin in case it is not loadable and keep on with the deletion process?

**Comment by meydominic** [comment]
@pinhead84 
That's something I thought about, too. Maybe with a note on the java doc/documentation that there is no guarantee the delete() method in plugin will be called.

**Comment by decebals** [comment]
I think that I found a solution to solve the problem in an elegant mode with few modifications.
My idea is to retrieve the plugin instance before the plugin will be unloaded.
See below the modifications as diff:

![image](https://user-images.githubusercontent.com/1248311/56055499-49550e80-5d62-11e9-8e29-416e14356e02.png)

@meydominic 
Please make above modificati,ons on you machine. Build and test the new PF4J version on you use case (application). If the result is OK please let me know to commit the modifications on GitHub. Thanks!

**Comment by meydominic** [comment]
Will test it when I am on work on monday and will report back. Thanks.

**Comment by meydominic** [comment]
Your approach works fine 👍
