### ISSUE TITLE
plugin obfucation

### ISSUE THREAD

**Issue by otmanel31** [pf4j/pf4j#325]
Hi, is it possible to load an obfuscating plugin in the boot app ? i try it and it doesn't work for me. I use stringer obfuscator and only obfuscating the plugin one that is in your demo folder.
Thanks by advance

**Comment by otmanel31** [comment]
I forgot .. i use pf4j for spring (java) app

**Comment by decebals** [comment]
Please give us more information. I don't have experience with obfuscators (I know about them but I didn't use). What doesn't work (share with us the message, stack trace, ...).

**Comment by otmanel31** [comment]
Hi thanks for your quick reply ..... when i execute my maven command to clean and install the demo (so inside the demo folder), the build is ok. Then i add the zip of plugin 1 into plugins folder. Then obfuscate plugin is detected. When i run the main programm (APP), i'm only able to see  "Whazzup" message that is inside the app program but not the "welcome" message. It works with non obfuscate plugin.
I just found an exception that's i'm going to share. Not class found exception of welcome plugin ....  but the welcomePlugin class is inside the package.

> ########################################
              PF4J-SPRING
########################################
2019-06-28 11:29:26,164 DEBUG org.springframework.core.env.StandardEnvironment - Adding [systemProperties] PropertySource with lowest search precedence
2019-06-28 11:29:26,168 DEBUG org.springframework.core.env.StandardEnvironment - Adding [systemEnvironment] PropertySource with lowest search precedence
2019-06-28 11:29:26,168 DEBUG org.springframework.core.env.StandardEnvironment - Initialized StandardEnvironment with PropertySources [systemProperties,systemEnvironment]
2019-06-28 11:29:26,225 INFO org.springframework.context.annotation.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@1376c05c: startup date [Fri Jun 28 11:29:26 CEST 2019]; root of context hierarchy
2019-06-28 11:29:26,225 DEBUG org.springframework.context.annotation.AnnotationConfigApplicationContext - Bean factory for org.springframework.context.annotation.AnnotationConfigApplicationContext@1376c05c: org.springframework.beans.factory.support.DefaultListableBeanFactory@458ad742: defining beans [org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,springConfiguration]; root of factory hierarchy
2019-06-28 11:29:26,235 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'org.springframework.context.annotation.internalConfigurationAnnotationProcessor'
2019-06-28 11:29:26,236 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating instance of bean 'org.springframework.context.annotation.internalConfigurationAnnotationProcessor'
2019-06-28 11:29:26,250 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Eagerly caching bean 'org.springframework.context.annotation.internalConfigurationAnnotationProcessor' to allow for resolving potential circular references
2019-06-28 11:29:26,252 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'org.springframework.context.annotation.internalConfigurationAnnotationProcessor'
2019-06-28 11:29:26,279 DEBUG org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.pf4j.demo.SpringConfiguration.greetings()
2019-06-28 11:29:26,280 DEBUG org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.pf4j.demo.SpringConfiguration.pluginManager()
2019-06-28 11:29:26,343 DEBUG org.springframework.context.annotation.ConfigurationClassEnhancer - Successfully enhanced org.pf4j.demo.SpringConfiguration; enhanced class name is: org.pf4j.demo.SpringConfiguration$$EnhancerBySpringCGLIB$$d13c994c
2019-06-28 11:29:26,343 DEBUG org.springframework.context.annotation.ConfigurationClassPostProcessor - Replacing bean definition 'springConfiguration' existing class name 'org.pf4j.demo.SpringConfiguration' with enhanced class name 'org.pf4j.demo.SpringConfiguration$$EnhancerBySpringCGLIB$$d13c994c'
2019-06-28 11:29:26,347 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'org.springframework.context.annotation.internalAutowiredAnnotationProcessor'
2019-06-28 11:29:26,348 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating instance of bean 'org.springframework.context.annotation.internalAutowiredAnnotationProcessor'
2019-06-28 11:29:26,349 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Eagerly caching bean 'org.springframework.context.annotation.internalAutowiredAnnotationProcessor' to allow for resolving potential circular references
2019-06-28 11:29:26,349 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'org.springframework.context.annotation.internalAutowiredAnnotationProcessor'
2019-06-28 11:29:26,350 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'org.springframework.context.annotation.internalRequiredAnnotationProcessor'
2019-06-28 11:29:26,351 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating instance of bean 'org.springframework.context.annotation.internalRequiredAnnotationProcessor'
2019-06-28 11:29:26,352 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Eagerly caching bean 'org.springframework.context.annotation.internalRequiredAnnotationProcessor' to allow for resolving potential circular references
2019-06-28 11:29:26,352 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'org.springframework.context.annotation.internalRequiredAnnotationProcessor'
2019-06-28 11:29:26,354 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'org.springframework.context.annotation.internalCommonAnnotationProcessor'
2019-06-28 11:29:26,354 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating instance of bean 'org.springframework.context.annotation.internalCommonAnnotationProcessor'
2019-06-28 11:29:26,357 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Eagerly caching bean 'org.springframework.context.annotation.internalCommonAnnotationProcessor' to allow for resolving potential circular references
2019-06-28 11:29:26,357 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'org.springframework.context.annotation.internalCommonAnnotationProcessor'
2019-06-28 11:29:26,358 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor'
2019-06-28 11:29:26,359 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating instance of bean 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor'
2019-06-28 11:29:26,360 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Eagerly caching bean 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor' to allow for resolving potential circular references
2019-06-28 11:29:26,360 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor'
2019-06-28 11:29:26,361 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'org.springframework.context.annotation.ConfigurationClassPostProcessor.enhancedConfigurationProcessor'
2019-06-28 11:29:26,362 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating instance of bean 'org.springframework.context.annotation.ConfigurationClassPostProcessor.enhancedConfigurationProcessor'
2019-06-28 11:29:26,366 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Eagerly caching bean 'org.springframework.context.annotation.ConfigurationClassPostProcessor.enhancedConfigurationProcessor' to allow for resolving potential circular references
2019-06-28 11:29:26,366 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'org.springframework.context.annotation.ConfigurationClassPostProcessor.enhancedConfigurationProcessor'
2019-06-28 11:29:26,369 DEBUG org.springframework.context.annotation.AnnotationConfigApplicationContext - Unable to locate MessageSource with name 'messageSource': using default [org.springframework.context.support.DelegatingMessageSource@75881071]
2019-06-28 11:29:26,371 DEBUG org.springframework.context.annotation.AnnotationConfigApplicationContext - Unable to locate ApplicationEventMulticaster with name 'applicationEventMulticaster': using default [org.springframework.context.event.SimpleApplicationEventMulticaster@7e0e6aa2]
2019-06-28 11:29:26,374 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@458ad742: defining beans [org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,springConfiguration,org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor,org.springframework.context.annotation.ConfigurationClassPostProcessor.enhancedConfigurationProcessor,greetings,pluginManager]; root of factory hierarchy
2019-06-28 11:29:26,375 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'org.springframework.context.annotation.internalConfigurationAnnotationProcessor'
2019-06-28 11:29:26,376 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'org.springframework.context.annotation.internalAutowiredAnnotationProcessor'
2019-06-28 11:29:26,377 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'org.springframework.context.annotation.internalRequiredAnnotationProcessor'
2019-06-28 11:29:26,377 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'org.springframework.context.annotation.internalCommonAnnotationProcessor'
2019-06-28 11:29:26,379 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'springConfiguration'
2019-06-28 11:29:26,382 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating instance of bean 'springConfiguration'
2019-06-28 11:29:26,385 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Eagerly caching bean 'springConfiguration' to allow for resolving potential circular references
2019-06-28 11:29:26,396 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'springConfiguration'
2019-06-28 11:29:26,396 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor'
2019-06-28 11:29:26,400 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'org.springframework.context.annotation.ConfigurationClassPostProcessor.enhancedConfigurationProcessor'
2019-06-28 11:29:26,401 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'pluginManager'
2019-06-28 11:29:26,401 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating instance of bean 'pluginManager'
2019-06-28 11:29:26,404 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'springConfiguration'
2019-06-28 11:29:26,436 INFO org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
2019-06-28 11:29:26,437 INFO org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
2019-06-28 11:29:26,441 INFO org.pf4j.DefaultPluginManager - PF4J version 2.5.0 in 'deployment' mode
2019-06-28 11:29:26,442 DEBUG org.springframework.context.annotation.CommonAnnotationBeanPostProcessor - Found init method on class [org.pf4j.spring.SpringPluginManager]: public void org.pf4j.spring.SpringPluginManager.init()
2019-06-28 11:29:26,444 DEBUG org.springframework.context.annotation.CommonAnnotationBeanPostProcessor - Registered init method on class [org.pf4j.spring.SpringPluginManager]: org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement@316510
2019-06-28 11:29:26,446 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Eagerly caching bean 'pluginManager' to allow for resolving potential circular references
2019-06-28 11:29:26,454 DEBUG org.springframework.context.annotation.CommonAnnotationBeanPostProcessor - Invoking init method on bean 'pluginManager': public void org.pf4j.spring.SpringPluginManager.init()
2019-06-28 11:29:26,454 DEBUG org.pf4j.AbstractPluginManager - Lookup plugins in 'plugins'
2019-06-28 11:29:26,509 DEBUG org.pf4j.AbstractPluginManager - Found 1 possible plugins: [plugins\pf4j-spring-demo-plugin1-0.6.0-SNAPSHOT]
2019-06-28 11:29:26,510 DEBUG org.pf4j.AbstractPluginManager - Use 'org.pf4j.CompoundPluginDescriptorFinder@516be40f' to find plugins descriptors
2019-06-28 11:29:26,512 DEBUG org.pf4j.AbstractPluginManager - Finding plugin descriptor for plugin 'plugins\pf4j-spring-demo-plugin1-0.6.0-SNAPSHOT'
2019-06-28 11:29:26,516 DEBUG org.pf4j.CompoundPluginDescriptorFinder - 'org.pf4j.PropertiesPluginDescriptorFinder@3c0a50da' is applicable for plugin 'plugins\pf4j-spring-demo-plugin1-0.6.0-SNAPSHOT'
2019-06-28 11:29:26,517 DEBUG org.pf4j.PropertiesPluginDescriptorFinder - Lookup plugin descriptor in 'plugins\pf4j-spring-demo-plugin1-0.6.0-SNAPSHOT\plugin.properties'
2019-06-28 11:29:26,523 DEBUG org.pf4j.CompoundPluginDescriptorFinder - Cannot find 'plugins\pf4j-spring-demo-plugin1-0.6.0-SNAPSHOT\plugin.properties' path
2019-06-28 11:29:26,525 DEBUG org.pf4j.CompoundPluginDescriptorFinder - Try to continue with the next finder
2019-06-28 11:29:26,527 DEBUG org.pf4j.CompoundPluginDescriptorFinder - 'org.pf4j.ManifestPluginDescriptorFinder@77be656f' is applicable for plugin 'plugins\pf4j-spring-demo-plugin1-0.6.0-SNAPSHOT'
2019-06-28 11:29:26,535 DEBUG org.pf4j.ManifestPluginDescriptorFinder - Lookup plugin descriptor in 'plugins\pf4j-spring-demo-plugin1-0.6.0-SNAPSHOT\META-INF\MANIFEST.MF'
2019-06-28 11:29:26,553 DEBUG org.pf4j.AbstractPluginManager - Found descriptor PluginDescriptor [pluginId=welcome-plugin, pluginClass=org.pf4j.demo.welcome.WelcomePlugin, version=0.0.1, provider=Decebal Suiu, dependencies=[], description=, requires=*, license=null]
2019-06-28 11:29:26,555 DEBUG org.pf4j.AbstractPluginManager - Class 'org.pf4j.demo.welcome.WelcomePlugin' for plugin 'plugins\pf4j-spring-demo-plugin1-0.6.0-SNAPSHOT'
2019-06-28 11:29:26,556 DEBUG org.pf4j.AbstractPluginManager - Loading plugin 'plugins\pf4j-spring-demo-plugin1-0.6.0-SNAPSHOT'
2019-06-28 11:29:26,558 DEBUG org.pf4j.CompoundPluginLoader - 'org.pf4j.DefaultPluginLoader@551bdc27' is applicable for plugin 'plugins\pf4j-spring-demo-plugin1-0.6.0-SNAPSHOT'
2019-06-28 11:29:26,559 DEBUG org.pf4j.AbstractPluginManager - Loaded plugin 'plugins\pf4j-spring-demo-plugin1-0.6.0-SNAPSHOT' with class loader 'org.pf4j.PluginClassLoader@6b1274d2'
2019-06-28 11:29:26,560 DEBUG org.pf4j.AbstractPluginManager - Creating wrapper for plugin 'plugins\pf4j-spring-demo-plugin1-0.6.0-SNAPSHOT'
2019-06-28 11:29:26,562 DEBUG org.pf4j.AbstractPluginManager - Created wrapper 'PluginWrapper [descriptor=PluginDescriptor [pluginId=welcome-plugin, pluginClass=org.pf4j.demo.welcome.WelcomePlugin, version=0.0.1, provider=Decebal Suiu, dependencies=[], description=, requires=*, license=null], pluginPath=plugins\pf4j-spring-demo-plugin1-0.6.0-SNAPSHOT]' for plugin 'plugins\pf4j-spring-demo-plugin1-0.6.0-SNAPSHOT'
2019-06-28 11:29:26,562 DEBUG org.pf4j.DependencyResolver - Graph:
   welcome-plugin -> []
2019-06-28 11:29:26,563 DEBUG org.pf4j.DependencyResolver - Plugins order: [welcome-plugin]
2019-06-28 11:29:26,564 INFO org.pf4j.AbstractPluginManager - Plugin 'welcome-plugin@0.0.1' resolved
2019-06-28 11:29:26,564 INFO org.pf4j.AbstractPluginManager - Start plugin 'welcome-plugin@0.0.1'
2019-06-28 11:29:26,564 DEBUG org.pf4j.DefaultPluginFactory - Create instance for plugin 'org.pf4j.demo.welcome.WelcomePlugin'
2019-06-28 11:29:26,566 ERROR org.pf4j.DefaultPluginFactory - org.pf4j.demo.welcome.WelcomePlugin
java.lang.ClassNotFoundException: org.pf4j.demo.welcome.WelcomePlugin
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.pf4j.PluginClassLoader.loadClass(PluginClassLoader.java:126)
        at org.pf4j.DefaultPluginFactory.create(DefaultPluginFactory.java:46)
        at org.pf4j.PluginWrapper.getPlugin(PluginWrapper.java:78)
        at org.pf4j.AbstractPluginManager.startPlugins(AbstractPluginManager.java:328)
        at org.pf4j.spring.SpringPluginManager.init(SpringPluginManager.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:349)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:300)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:407)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1545)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:294)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:703)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
        at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
        at org.pf4j.demo.Boot.main(Boot.java:35)
2019-06-28 11:29:26,571 ERROR org.pf4j.AbstractPluginManager -
java.lang.NullPointerException
        at org.pf4j.AbstractPluginManager.startPlugins(AbstractPluginManager.java:328)
        at org.pf4j.spring.SpringPluginManager.init(SpringPluginManager.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:349)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:300)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:407)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1545)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:294)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:703)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
        at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
        at org.pf4j.demo.Boot.main(Boot.java:35)
2019-06-28 11:29:26,578 DEBUG org.pf4j.LegacyExtensionFinder - Reading extensions storages from classpath
2019-06-28 11:29:26,578 DEBUG org.pf4j.LegacyExtensionFinder - Read 'file:/C:/Users/oelkenz/Documents/obfus/pf4j-spring/demo/app/target/pf4j-spring-demo-app-0.6.0-SNAPSHOT/pf4j-spring-demo-app-0.6.0-SNAPSHOT.jar!/META-INF/extensions.idx'
2019-06-28 11:29:26,581 DEBUG org.pf4j.AbstractExtensionFinder - Found possible 1 extensions:
2019-06-28 11:29:26,581 DEBUG org.pf4j.AbstractExtensionFinder -    org.pf4j.demo.WhazzupGreeting
2019-06-28 11:29:26,582 DEBUG org.pf4j.LegacyExtensionFinder - Reading extensions storages from plugins
2019-06-28 11:29:26,583 DEBUG org.pf4j.LegacyExtensionFinder - Reading extensions storage from plugin 'welcome-plugin'
2019-06-28 11:29:26,584 DEBUG org.pf4j.LegacyExtensionFinder - Cannot find 'META-INF/extensions.idx'
2019-06-28 11:29:26,585 DEBUG org.pf4j.AbstractExtensionFinder - No extensions found
2019-06-28 11:29:26,585 DEBUG org.pf4j.spring.ExtensionsInjector - Register extension 'org.pf4j.demo.WhazzupGreeting' as bean
2019-06-28 11:29:26,587 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'pluginManager'
2019-06-28 11:29:26,590 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'greetings'
2019-06-28 11:29:26,591 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating instance of bean 'greetings'
2019-06-28 11:29:26,592 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'springConfiguration'
2019-06-28 11:29:26,596 DEBUG org.springframework.beans.factory.annotation.InjectionMetadata - Registered injected element on class [org.pf4j.demo.Greetings]: AutowiredFieldElement for private java.util.List org.pf4j.demo.Greetings.greetings
2019-06-28 11:29:26,597 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Eagerly caching bean 'greetings' to allow for resolving potential circular references
2019-06-28 11:29:26,599 DEBUG org.springframework.beans.factory.annotation.InjectionMetadata - Processing injected method of bean 'greetings': AutowiredFieldElement for private java.util.List org.pf4j.demo.Greetings.greetings
2019-06-28 11:29:26,604 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'org.pf4j.demo.WhazzupGreeting'
2019-06-28 11:29:26,606 DEBUG org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor - Autowiring by type from bean name 'greetings' to bean named 'org.pf4j.demo.WhazzupGreeting'
2019-06-28 11:29:26,613 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'greetings'
2019-06-28 11:29:26,614 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'pluginManager'
2019-06-28 11:29:26,616 DEBUG org.springframework.context.annotation.AnnotationConfigApplicationContext - Unable to locate LifecycleProcessor with name 'lifecycleProcessor': using default [org.springframework.context.support.DefaultLifecycleProcessor@123f1134]
2019-06-28 11:29:26,617 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'lifecycleProcessor'
2019-06-28 11:29:26,619 DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Searching for key 'spring.liveBeansView.mbeanDomain' in [systemProperties]
2019-06-28 11:29:26,620 DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Searching for key 'spring.liveBeansView.mbeanDomain' in [systemEnvironment]
2019-06-28 11:29:26,623 DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'spring.liveBeansView.mbeanDomain' in any property source. Returning [null]
2019-06-28 11:29:26,624 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'greetings'
Found 1 extensions for extension point 'org.pf4j.demo.api.Greeting'
>>> Whazzup
2019-06-28 11:29:26,627 DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'pluginManager'

**Comment by otmanel31** [comment]
I'm going to investigate deeply .....

**Comment by decebals** [comment]
It depends on what obfuscator does. If it changes the class name or names of methods defined in `Plugin` (start, stop, delete) then you are in trouble.
Let takes an example. You have a plugin with the plugin class `MyPlugin`. You define in the descriptor of plugin that the plugin class is `MyPlugin`. If the obfuscator obfuscates the plugin class name in `ABC` then the plugin manager cannot find and load the plugin class defined in descriptor (`MyPlugin`).

**Comment by otmanel31** [comment]
I use Stringer obfuscator ... 
I understood but the class and classname in generated code are the same only code inside is obfuscate.
What do you mean by descriptor ? is the for the classname in the pom plugin1 ?

**Comment by decebals** [comment]
> What do you mean by descriptor ? is the for the classname in the pom plugin1 ?

https://github.com/pf4j/pf4j/blob/master/demo/plugins/plugin1/plugin.properties#L2 (or MANIFEST.MF)

**Comment by otmanel31** [comment]
ok yes i already check it ...

**Comment by otmanel31** [comment]
here my manifest 

> Manifest-Version: 1.0
Plugin-Dependencies: 
Implementation-Title: Demo Plugin #1
Implementation-Version: 0.6.0-SNAPSHOT
Protected-Notice: AV contact email - primary@licelus.com
Archiver-Version: Plexus Archiver
Built-By: oelkenz
Specification-Title: Demo Plugin #1
Implementation-Vendor-Id: org.pf4j.demo
JAR-Signature: +1IgEJiXbs4SA3jNMpnlCZRhER6wBIIWGAzmLWXEu+H6dFhd
Plugin-Version: 0.0.1
Protected-By: 9.1.15 Stringer (20190521)
Plugin-Id: welcome-plugin
Plugin-Provider: Decebal Suiu
Plugin-Class: org.pf4j.demo.welcome.WelcomePlugin
Created-By: Apache Maven 3.5.3
Build-Jdk: 1.8.0_211
Specification-Version: 0.6.0-SNAPSHOT

Evething is ok. Then in the extension.idx, i found the extension class name:

> # Generated by PF4J

> org.pf4j.demo.welcome.WelcomePlugin$WelcomeGreeting

**Comment by otmanel31** [comment]
And welcomplugin class is in the generated package ...  May  be obfuscate an plugin is a little bit complex or impossible

**Comment by decebals** [comment]
The error message is simple
```
2019-06-28 11:29:26,564 DEBUG org.pf4j.DefaultPluginFactory - Create instance for plugin 'org.pf4j.demo.welcome.WelcomePlugin'
2019-06-28 11:29:26,566 ERROR org.pf4j.DefaultPluginFactory - org.pf4j.demo.welcome.WelcomePlugin
java.lang.ClassNotFoundException: org.pf4j.demo.welcome.WelcomePlugin
```

So, the plugin manager try to create the plugin specified by you in descriptor (`org.pf4j.demo.welcome.WelcomePlugin`) but this class doesn't exist.

My question is also simple:
Do you have or not a class `org.pf4j.demo.welcome.WelcomePlugin` in plugin jar (classpath)?

My feeling that the obfuscator obfuscate the class name and from this reason the class specified by you in descriptor doesn't exists.

More than that I can not help you.

**Comment by otmanel31** [comment]
Thanks for your advice .... i found the issue ...i ran my obfuscator plugin (which is Stringer obfuscator) after the maven-antrun-plugin (in pom.xml file)  ... by executing before, that's work. I know this is not a pf4j issue ... now i understand how your framework work. Thanks
