### ISSUE TITLE
StackOverflow in AbstractExtensionFinder.findExtensionAnnotation()

### ISSUE THREAD

**Issue by metaschell** [pf4j/pf4j#363]
I create an extension and registered it using the `extension.idx` file and the class is properly loaded. My class has no `@Extension` annotation though (this should stay like this, I manually created the `extensions.idx` file), but when scanning for the `@Extension` annotation in 
 `org.pf4j.AbstractExtensionFinder.findExtensionAnnotation(Class<?>)` the `findExtensionAnnotation()` method is calling itself recursively. Theoretically, it should simply return `null` if there is no such annotation, but the problem here is that if there are _any_  other annotations this leads to a StackOverflowError as any other annotation would have any of the `java.lang.annotations` annotations such as `@Scope`, `@Retention`, and `@Documented` which in turn uses these three annotations again:
`@MyAnnotation -> @Retention -> @Documented -> @Retention -> @Documented ...`

A potential solution would be to not do the recursion for any annotation in the java.lang.* packages.

BTW, it is difficult to work around this problem as all methods are private so they cannot be overridden in order to catch the problem and move on. I understand that this is a philosophical question regarding hiding vs. (partially) exposing internals, but currently there is no way around that unless overriding all of `org.pf4j.AbstractExtensionFinder.find(String)` with all related methods...

**(Partial) Stacktrace:**
>    Caused by: java.lang.StackOverflowError: null
        at java.util.LinkedHashMap$LinkedHashIterator.<init>(LinkedHashMap.java:706) ~[na:1.8.0_222]
        at java.util.LinkedHashMap$LinkedValueIterator.<init>(LinkedHashMap.java:745) ~[na:1.8.0_222]
        at java.util.LinkedHashMap$LinkedValues.iterator(LinkedHashMap.java:596) ~[na:1.8.0_222]
        at java.util.AbstractCollection.toArray(AbstractCollection.java:180) ~[na:1.8.0_222]
        at sun.reflect.annotation.AnnotationParser.toArray(AnnotationParser.java:865) ~[na:1.8.0_222]
        at java.lang.Class.getAnnotations(Class.java:3446) ~[na:1.8.0_222]
        at org.pf4j.AbstractExtensionFinder.findExtensionAnnotation(AbstractExtensionFinder.java:357) ~[na:na]
        at org.pf4j.AbstractExtensionFinder.findExtensionAnnotation(AbstractExtensionFinder.java:359) ~[na:na]
        at org.pf4j.AbstractExtensionFinder.findExtensionAnnotation(AbstractExtensionFinder.java:359) ~[na:na]
        at org.pf4j.AbstractExtensionFinder.findExtensionAnnotation(AbstractExtensionFinder.java:359) ~[na:na]
        at org.pf4j.AbstractExtensionFinder.findExtensionAnnotation(AbstractExtensionFinder.java:359) ~[na:na]
        at org.pf4j.AbstractExtensionFinder.findExtensionAnnotation(AbstractExtensionFinder.java:359) ~[na:na]
        at org.pf4j.AbstractExtensionFinder.findExtensionAnnotation(AbstractExtensionFinder.java:359) ~[na:na]
        at org.pf4j.AbstractExtensionFinder.findExtensionAnnotation(AbstractExtensionFinder.java:359) ~[na:na]
        at org.pf4j.AbstractExtensionFinder.findExtensionAnnotation(AbstractExtensionFinder.java:359) ~[na:na]
        at org.pf4j.AbstractExtensionFinder.findExtensionAnnotation(AbstractExtensionFinder.java:359) ~[na:na]
        at org.pf4j.AbstractExtensionFinder.findExtensionAnnotation(AbstractExtensionFinder.java:359) ~[na:na]
        at org.pf4j.AbstractExtensionFinder.findExtensionAnnotation(AbstractExtensionFinder.java:359) ~[na:na]
        at org.pf4j.AbstractExtensionFinder.findExtensionAnnotation(AbstractExtensionFinder.java:359) ~[na:na]
        ...

**Example class:**
(note the class would rather implement an interface extending ExtensionPoint, but that should not make a difference here)

    package com.example;

    import org.pf4j.ExtensionPoint;

    @SomeAnnotation
    public class ExampleExtension implements ExtensionPoint {
        public void doSomething() {
            System.out.println("Hello, world");
        }
    }

**Registration file** (`META-INF/extensions.idx`)

    com.example.ExampleExtension

**Comment by decebals** [comment]
@metaschell 
Sorry, but I completely missed this issue.
I think that I understand your problem. The `AbstractExtensionFinder.findExtensionAnnotation` was introduced by https://github.com/pf4j/pf4j/pull/348:
![image](https://user-images.githubusercontent.com/1248311/73756798-d691a580-4770-11ea-9bbb-58f4131f1a40.png)

> A potential solution would be to not do the recursion for any annotation in the java.lang.* packages.

I think that for the moment is the best (simple and without to many modifications) solution. Can you submit a PR?

In the future I hope to avoid reflection for this part of PF4J (find extensions). We have all the information (extensions classes, extensions orders, extensions points) at compilation time (in annotation processor) and we can reuse this information at runtime (see https://github.com/pf4j/pf4j/issues/207).

**Comment by decebals** [comment]
@metaschell 
If you want to submit a PR would be nice. If you don't have time I will try to do it myself.
My intention is to release a new version in few days.

**Comment by metaschell** [comment]
@decebals I will likely not have time in the next two weeks so if you would like to have that fixed by then, feel free to go ahead. We have a local workaround in place

**Comment by metaschell** [comment]
> In the future I hope to avoid reflection for this part of PF4J (find extensions). We have all the information (extensions classes, extensions orders, extensions points) at compilation time (in annotation processor) and we can reuse them at runtime (see #207).

This is only the case if you actually use the annotation processor in the build which is not necessarily always the case... 

In our project we basically only use a custom ServiceLoader-based ExtensionFinder now.

**Comment by jetztgradnet** [comment]
Nice, thanks for fixing!
We are using a different approach now, but it is still good to see this closed, as other might stumble over the same issue.
