### ISSUE TITLE
working with maven release plugin or any plugin with verion x.y.z-LABEL

### ISSUE THREAD

**Issue by asafbennatan** [pf4j/pf4j#440]
the setup:
lets say i have two plugins 
the first is plugin-a-1.0.0-SNAPSHOT.jar and the second is plugin-b-1.0.0.jar ,
now i want to make plugin-b dependent on plugin-a .
usually the most appropriate way would be to set a maven property (in plugin-b POM) called plugin-a.version and use it in both the maven dependency section and the Plugin-Dependencies manifest entry so when a version is changed you dont have to change in both places.
now the issue:
if i set plugin-a.version variable as 1.0.0-SNAPSHOT , pf4j complains that:
`com.github.zafarkhaja.semver.expr.LexerException: null
	at com.github.zafarkhaja.semver.expr.Lexer.tokenize(Lexer.java:218)
	at com.github.zafarkhaja.semver.expr.ExpressionParser.parse(ExpressionParser.java:86)
	at com.github.zafarkhaja.semver.expr.ExpressionParser.parse(ExpressionParser.java:43)
	at com.github.zafarkhaja.semver.Version.satisfies(Version.java:325)`
if i try seperating it into two variables plugin-a.version-full plugin-a.version-numeric then 1.0.0-SNAPSHOT < 1.0.0 (as expected) and the runtime files due to incompatible plugin dependencies.
since maven release plugin is in high usage - what would be the correct way to develop and check plugins with version scheme of x.y.z.-SNAPSHOT?

**Comment by decebals** [comment]
> ok after some research it seems like the issue is with https://github.com/zafarkhaja/jsemver
which seems like is not being maintened anymore

https://github.com/zafarkhaja/jsemver/issues/56

One idea is to switch to [semver4j](https://github.com/vdurmont/semver4j), but it's not an easy decision because I don't know how many people use internally the jsemver's API, although they shouldn't because we have [VersionManager](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/VersionManager.java) interface.

Maybe it's a good idea to add a PR with another implementation of `VersionManager` (for example semver4j), to have something an alternative. Can you try to add this PR, and test it with your use case? 
Also, can you add a test in [DefaultVersionManagerTest](https://github.com/pf4j/pf4j/blob/master/pf4j/src/test/java/org/pf4j/DefaultVersionManagerTest.java) that fails on your use case?

In the end, related to this NPE. what is wrong in jsemver (the root of the problem)?  I ask you because I'm curious.

**Comment by asafbennatan** [comment]
@decebals
1.agree with the issues of switching to semver4j - also they still do not support condition expressions such as >= only parsing of versions and programmatically checking for condition.
2.yes will try doing so
3.actually the exception is a LexerException that is caused by jsemver failing to tokenize the '-SNAPSHOT' part of the 1.0.0-SNAPSHOT

**Comment by decebals** [comment]
@asafbennatan [jsemver](https://github.com/zafarkhaja/jsemver) has updated recently. If we need help, we have to create an issue on that project.

**Comment by decebals** [comment]
@asafbennatan Is it issue still relevant for you. Please add an issue on https://github.com/zafarkhaja/jsemver.

**Comment by asafbennatan** [comment]
it is, let me check - you mean its on the latest version of pf4j ?

**Comment by decebals** [comment]
Yes, please. 
In https://github.com/pf4j/pf4j/commit/a73185226d5591d0ac7b8ee508cd69f41fa0bfeb we updated `jsemver` to latest version (0.10.2) version. 
If the issue persist, please raise an issue on [jsemver](https://github.com/zafarkhaja/jsemver/issues).

**Comment by asafbennatan** [comment]
@decebals original NPE is resolved but now i get the following :
`Caused by: org.pf4j.DependencyResolver$DependenciesWrongVersionException: Dependencies '[WrongDependencyVersion{dependencyId='category-service', dependentId='flexicore-ui-service', existingVersion='8.1.0-SNAPSHOT', requiredVersion='>=8.1.0-SNAPSHOT'}]' have wrong version
	at org.pf4j.AbstractPluginManager.resolveDependencies(AbstractPluginManager.java:1073)
	at org.pf4j.AbstractPluginManager.resolvePlugins(AbstractPluginManager.java:820)
	at org.pf4j.AbstractPluginManager.loadPlugins(AbstractPluginManager.java:252)
`

i lost track - is this an expected behavior ?
