### ISSUE TITLE
Test failing due to mockito complaint about mocking javax.annotation.processins.Filer

### ISSUE THREAD

**Issue by pgrt** [pf4j/pf4j#445]
Hello,

While packaging pf4j for Debian, I met a failing test: _ensureReadingExtensionsProducesCorrectListOfExtensions_, with the below output. This was in a chroot with Debian unstable.

Best,
Pierre

`[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.201 s <<< FAILURE! - in org.pf4j.processor.ServiceProviderExtensionStorageTest
[ERROR] ensureReadingExtensionsProducesCorrectListOfExtensions  Time elapsed: 0.198 s  <<< ERROR!
org.mockito.exceptions.base.MockitoException: 

Mockito cannot mock this class: interface javax.annotation.processing.Filer.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.

Java               : 11
JVM vendor name    : Debian
JVM vendor version : 11.0.11+9-post-Debian-1
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 11.0.11+9-post-Debian-1
JVM info           : mixed mode, sharing
OS name            : Linux
OS version         : 5.10.0-6-amd64

Underlying exception : java.lang.IllegalStateException: Cannot define a type in net.bytebuddy.dynamic.loading.MultipleParentClassLoader@6e1d8f9e with lookup based on jdk.internal.loader.ClassLoaders$AppClassLoader@55054057
        at org.pf4j.processor.ServiceProviderExtensionStorageTest.ensureReadingExtensionsProducesCorrectListOfExtensions(ServiceProviderExtensionStorageTest.java:82)
Caused by: java.lang.IllegalStateException: Cannot define a type in net.bytebuddy.dynamic.loading.MultipleParentClassLoader@6e1d8f9e with lookup based on jdk.internal.loader.ClassLoaders$AppClassLoader@55054057
        at org.pf4j.processor.ServiceProviderExtensionStorageTest.ensureReadingExtensionsProducesCorrectListOfExtensions(ServiceProviderExtensionStorageTest.java:82)`

**Comment by pgrt** [comment]
Hello,

Thanks for caring; if so, I assume you can safely close the issue. I can omit the test when building on my side.

I should have said I used version 2.23.0 of mockito when I got this issue; maybe this is the reason.

Best regards,
Pierre
