### ISSUE TITLE
ClassNotFoundException when executing the Boot class in a project based on the pf4j-quickstart archetype

### ISSUE THREAD

**Issue by PatrickHaas** [pf4j/pf4j#448]
Hi guys,
i just tried creating a project based on your archetype 'pf4j-quickstart'. When executing the Boot class via IDE, in my case it's IntelliJ IDEA, I'm getting the following exceptions:
`2021-05-20 23:51:05,296 ERROR org.pf4j.DefaultPluginFactory - org.example.welcome.WelcomePlugin
java.lang.ClassNotFoundException: org.example.welcome.WelcomePlugin
	at org.pf4j.PluginClassLoader.loadClass(PluginClassLoader.java:144) ~[pf4j-3.6.0.jar:3.6.0]
	at org.pf4j.DefaultPluginFactory.create(DefaultPluginFactory.java:46) [pf4j-3.6.0.jar:3.6.0]
	at org.pf4j.PluginWrapper.getPlugin(PluginWrapper.java:81) [pf4j-3.6.0.jar:3.6.0]
	at org.pf4j.AbstractPluginManager.startPlugins(AbstractPluginManager.java:358) [pf4j-3.6.0.jar:3.6.0]
	at org.example.Boot.main(Boot.java:28) [classes/:?]
2021-05-20 23:51:05,303 ERROR org.pf4j.AbstractPluginManager - Unable to start plugin 'welcome-plugin@1.0-SNAPSHOT'
java.lang.NullPointerException: null
	at org.pf4j.AbstractPluginManager.startPlugins(AbstractPluginManager.java:358) [pf4j-3.6.0.jar:3.6.0]
	at org.example.Boot.main(Boot.java:28) [classes/:?]
2021-05-20 23:51:05,303 INFO org.pf4j.AbstractPluginManager - Start plugin 'hello-plugin@1.0-SNAPSHOT'
2021-05-20 23:51:05,303 DEBUG org.pf4j.DefaultPluginFactory - Create instance for plugin 'org.example.hello.HelloPlugin'
2021-05-20 23:51:05,303 ERROR org.pf4j.DefaultPluginFactory - org.example.hello.HelloPlugin
java.lang.ClassNotFoundException: org.example.hello.HelloPlugin
	at org.pf4j.PluginClassLoader.loadClass(PluginClassLoader.java:144) ~[pf4j-3.6.0.jar:3.6.0]
	at org.pf4j.DefaultPluginFactory.create(DefaultPluginFactory.java:46) [pf4j-3.6.0.jar:3.6.0]
	at org.pf4j.PluginWrapper.getPlugin(PluginWrapper.java:81) [pf4j-3.6.0.jar:3.6.0]
	at org.pf4j.AbstractPluginManager.startPlugins(AbstractPluginManager.java:358) [pf4j-3.6.0.jar:3.6.0]
	at org.example.Boot.main(Boot.java:28) [classes/:?]
2021-05-20 23:51:05,303 ERROR org.pf4j.AbstractPluginManager - Unable to start plugin 'hello-plugin@1.0-SNAPSHOT'
java.lang.NullPointerException: null
	at org.pf4j.AbstractPluginManager.startPlugins(AbstractPluginManager.java:358) [pf4j-3.6.0.jar:3.6.0]
	at org.example.Boot.main(Boot.java:28) [classes/:?]`

Did I miss something?

best regards
patrick

**Comment by PatrickHaas** [comment]
Activating development-mode via
`System.setProperty("pf4j.mode", "development");`
fixed it for me.
