### ISSUE TITLE
Hi Team, 

### ISSUE THREAD

**Issue by Sangeeta-Yelgod-by** [pf4j/pf4j#465]
Hi Team,
I am facing few strange issues while working with pf4j library.. 
1. In the directory I have 3 version of plugins placed 
D:\JDA\wmwlmdisc\les\files\connector\NAZ01
1. connector-orchestration-plugin-2021.2.10.jar - latest once i am expecting this plugin to start 
2. connector-orchestration-plugin-2021.1.10.jar
3. \connector-orchestration-plugin-2021.1.8.jar

but from below logs could see connector-orchestration-plugin@2021.1.10 is starting
2021-07-25 03:12:02.644 [main]  INFO  org.pf4j.AbstractPluginManager - Plugin 'connector-orchestration-plugin@2021.1.10' resolved**

I am not able to figure out why this is happening ..need help here .. thank you

 There is an already loaded plugin (PluginWrapper [descriptor=PluginDescriptor [pluginId=connector-orchestration-plugin, pluginClass=com.blueyonder.logistics.plugin.orchestration.OrchestrationPlugIn, version=2021.1.10, provider=Blue Yonder, dependencies=[], description=, requires=*, license=null], pluginPath=D:\JDA\wmwlmdisc\les\files\connector\NAZ01\connector-orchestration-plugin-2021.1.10.jar]) with the same id (connector-orchestration-plugin) as the plugin at path 'D:\JDA\wmwlmdisc\les\files\connector\NAZ01\connector-orchestration-plugin-2021.2.10.jar'. Simultaneous loading of plugins with the same PluginId is not currently supported.
As a workaround you may include PluginVersion and PluginProvider in PluginId.
org.pf4j.PluginRuntimeException: There is an already loaded plugin (PluginWrapper [descriptor=PluginDescriptor [pluginId=connector-orchestration-plugin, pluginClass=com.blueyonder.logistics.plugin.orchestration.OrchestrationPlugIn, version=2021.1.10, provider=Blue Yonder, dependencies=[], description=, requires=*, license=null], pluginPath=D:\JDA\wmwlmdisc\les\files\connector\NAZ01\connector-orchestration-plugin-2021.1.10.jar]) with the same id (connector-orchestration-plugin) as the plugin at path 'D:\JDA\wmwlmdisc\les\files\connector\NAZ01\connector-orchestration-plugin-2021.2.10.jar'. Simultaneous loading of plugins with the same PluginId is not currently supported.
As a workaround you may include PluginVersion and PluginProvider in PluginId.
	at org.pf4j.AbstractPluginManager.loadPluginFromPath(AbstractPluginManager.java:802) ~[connector-2020.4.1.jar:?]
	at org.pf4j.DefaultPluginManager.loadPluginFromPath(DefaultPluginManager.java:130) ~[connector-2020.4.1.jar:?]
	at org.pf4j.AbstractPluginManager.loadPlugins(AbstractPluginManager.java:224) [connector-2020.4.1.jar:?]
	at com.blueyonder.connector.shell.ShellApplication.startPluginManager(ShellApplication.java:64) [connector-2020.4.1.jar:?]
	at com.blueyonder.connector.shell.ShellApplication.initializeApp(ShellApplication.java:36) [connector-2020.4.1.jar:?]
	at com.blueyonder.connector.shell.ShellApplication.main(ShellApplication.java:32) [connector-2020.4.1.jar:?]
2021-07-25 03:12:02.473 [main]  ERROR org.pf4j.AbstractPluginManager - There is an already loaded plugin (PluginWrapper [descriptor=PluginDescriptor [pluginId=connector-orchestration-plugin, pluginClass=com.blueyonder.logistics.plugin.orchestration.OrchestrationPlugIn, version=2021.1.10, provider=Blue Yonder, dependencies=[], description=, requires=*, license=null], pluginPath=D:\JDA\wmwlmdisc\les\files\connector\NAZ01\connector-orchestration-plugin-2021.1.10.jar]) with the same id (connector-orchestration-plugin) as the plugin at path 'D:\JDA\wmwlmdisc\les\files\connector\NAZ01\connector-orchestration-plugin-2021.1.8.jar'. Simultaneous loading of plugins with the same PluginId is not currently supported.
As a workaround you may include PluginVersion and PluginProvider in PluginId.
org.pf4j.PluginRuntimeException: There is an already loaded plugin (PluginWrapper [descriptor=PluginDescriptor [pluginId=connector-orchestration-plugin, pluginClass=com.blueyonder.logistics.plugin.orchestration.OrchestrationPlugIn, version=2021.1.10, provider=Blue Yonder, dependencies=[], description=, requires=*, license=null], pluginPath=D:\JDA\wmwlmdisc\les\files\connector\NAZ01\connector-orchestration-plugin-2021.1.10.jar]) with the same id (connector-orchestration-plugin) as the plugin at path 'D:\JDA\wmwlmdisc\les\files\connector\NAZ01\connector-orchestration-plugin-2021.1.8.jar'. Simultaneous loading of plugins with the same PluginId is not currently supported.
As a workaround you may include PluginVersion and PluginProvider in PluginId.
	at org.pf4j.AbstractPluginManager.loadPluginFromPath(AbstractPluginManager.java:802) ~[connector-2020.4.1.jar:?]
	at org.pf4j.DefaultPluginManager.loadPluginFromPath(DefaultPluginManager.java:130) ~[connector-2020.4.1.jar:?]
	at org.pf4j.AbstractPluginManager.loadPlugins(AbstractPluginManager.java:224) [connector-2020.4.1.jar:?]
	at com.blueyonder.connector.shell.ShellApplication.startPluginManager(ShellApplication.java:64) [connector-2020.4.1.jar:?]
	at com.blueyonder.connector.shell.ShellApplication.initializeApp(ShellApplication.java:36) [connector-2020.4.1.jar:?]
	at com.blueyonder.connector.shell.ShellApplication.main(ShellApplication.java:32) [connector-2020.4.1.jar:?]
**2021-07-25 03:12:02.644 [main]  INFO  org.pf4j.AbstractPluginManager - Plugin 'connector-ingestion-plugin@2021.1.1' resolved
2021-07-25 03:12:02.644 [main]  INFO  org.pf4j.AbstractPluginManager - Plugin 'connector-orchestration-plugin@2021.1.10' resolved**
2021-07-25 03:12:02.644 [main]  INFO  org.pf4j.AbstractPluginManager - Plugin 'bootstrap-plugin@2020.4.1' resolved
2021-07-25 03:12:02.644 [main]  INFO  org.pf4j.AbstractPluginManager - Start plugin 'connector-ingestion-plugin@2021.1.1'
2021-07-25 03:12:02.660 [main] connector-ingestion-plugin INFO  com.blueyonder.logistics.plugin.ingestion.IngestionPlugIn - Plugin starting connector-ingestion-plugin 2021.1.1
```

_Originally posted by @Sangeeta-Yelgod-by in https://github.com/pf4j/pf4j/issues/377#issuecomment-889206907_

**Comment by decebals** [comment]
@Sangeeta-Yelgod-by 
The error is normal in your use case. You have three different versions of the same plugin (each plugin is identified by the `plugin-id` property). The error message is clear, if you need such behavior (not natural in my opinion) you need to include the plugin version in the plugin id property to have a unique plugin id for each version of the plugin.

**Comment by Sangeeta-Yelgod-by** [comment]
I have included the plugin-version as well .. below is the meta-data file and this issue is intermittent issue..  
**Manifest-Version: 1.0
Plugin-Id: connector-orchestration-plugin
Start-Class: com.blueyonder.logistics.plugin.orchestration.WMOrchestra
 tionConnectorApp
Spring-Boot-Classes: BOOT-INF/classes/
Plugin-Provider: Blue Yonder
Plugin-Version: 2021.2.10
Plugin-Class: com.blueyonder.logistics.plugin.orchestration.Orchestrat
 ionPlugIn
Spring-Boot-Lib: BOOT-INF/lib/
Spring-Boot-Version: 2.2.5.RELEASE
Main-Class: org.springframework.boot.loader.JarLauncher**

**Comment by decebals** [comment]
Closed with resolution described in https://github.com/pf4j/pf4j/issues/465#issuecomment-890330780.
