### ISSUE TITLE
Hi Team,

### ISSUE THREAD

**Issue by Sangeeta-Yelgod-by** [pf4j/pf4j#466]
Hi Team,
I am facing strange issue while working with pf4j library... Working window's 10 machine
When Pf4j library try to delete the older version of .jar on unload of plugin , I am getting the below error

2021-07-25 03:12:40.233 [PluginManager] connector-orchestration-plugin INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Shutdown initiated...
2021-07-25 03:12:40.233 [PluginManager] connector-orchestration-plugin INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Shutdown completed.
2021-07-25 03:12:40.233 [PluginManager]  INFO  com.blueyonder.logistics.plugin.orchestration.OrchestrationPlugIn - Plugin stopped connector-orchestration-plugin 2021.1.10
2021-07-25 03:12:40.233 [PluginManager]  INFO  org.pf4j.AbstractPluginManager - Unload plugin 'connector-orchestration-plugin@2021.1.10'
2021-07-25 03:12:40.233 [PluginManager]  ERROR com.blueyonder.connector.shell.PluginRefresher - Exception while trying to update plugin 'connector-orchestration-plugin'
org.pf4j.PluginRuntimeException: java.nio.file.FileSystemException: D:\JDA\wmwlmdisc\les\files\connector\NAZ01\connector-orchestration-plugin-2021.1.10.jar: The process cannot access the file because it is being used by another process.

	at org.pf4j.BasePluginRepository.deletePluginPath(BasePluginRepository.java:100) ~[connector-2020.4.1.jar:?]
	at org.pf4j.CompoundPluginRepository.deletePluginPath(CompoundPluginRepository.java:71) ~[connector-2020.4.1.jar:?]
	at org.pf4j.AbstractPluginManager.deletePlugin(AbstractPluginManager.java:318) ~[connector-2020.4.1.jar:?]
	at org.pf4j.update.UpdateManager.updatePlugin(UpdateManager.java:364) ~[connector-2020.4.1.jar:?]
	at com.blueyonder.connector.shell.PluginRefresher.checkForUpdatedPlugins(PluginRefresher.java:59) ~[connector-2020.4.1.jar:?]
	at com.blueyonder.connector.shell.PluginRefresher.refresh(PluginRefresher.java:32) ~[connector-2020.4.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_192]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_192]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_192]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.nio.file.FileSystemException: D:\JDA\wmwlmdisc\les\files\connector\NAZ01\connector-orchestration-plugin-2021.1.10.jar: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86) ~[?:1.8.0_192]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:1.8.0_192]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) ~[?:1.8.0_192]
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269) ~[?:1.8.0_192]
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103) ~[?:1.8.0_192]
	at java.nio.file.Files.delete(Files.java:1126) ~[?:1.8.0_192]
	at org.pf4j.util.FileUtils$1.visitFile(FileUtils.java:93) ~[connector-2020.4.1.jar:?]
	at org.pf4j.util.FileUtils$1.visitFile(FileUtils.java:88) ~[connector-2020.4.1.jar:?]
	at java.nio.file.Files.walkFileTree(Files.java:2670) ~[?:1.8.0_192]
	at java.nio.file.Files.walkFileTree(Files.java:2742) ~[?:1.8.0_192]
	at org.pf4j.util.FileUtils.delete(FileUtils.java:88) ~[connector-2020.4.1.jar:?]
	at org.pf4j.BasePluginRepository.deletePluginPath(BasePluginRepository.java:95) ~[connector-2020.4.1.jar:?]
	... 12 more
2021-07-25 03:12:40.233 [PluginManager]  INFO  com.blueyonder.connector.shell.PluginRefresher - Found 1 available plugins
2021-07-25 03:12:40.233 [PluginManager]  INFO  com.blueyonder.connector.shell.PluginRefresher - Found available plugin 'connector-orchestration-plugin'
2021-07-25 03:12:40.233 [PluginManager]  INFO  com.blueyonder.connector.shell.plugin.bootstrap.ExternalArtifactProviderImpl - Downloading  connector-orchestration-plugin-2021.2.10.jar .....
2021-07-25 03:12:47.093 [PluginManager]  ERROR com.blueyonder.connector.shell.PluginRefresher - Exception while trying to install plugin 'connector-orchestration-plugin'
org.pf4j.PluginRuntimeException: Failed to write file 'D:\JDA\wmwlmdisc\les\files\connector\NAZ01\connector-orchestration-plugin-2021.2.10.jar' to plugins folder

_Originally posted by @Sangeeta-Yelgod-by in https://github.com/pf4j/pf4j/issues/377#issuecomment-889206907_

**Comment by decebals** [comment]
Duplication of #465.
