### ISSUE TITLE
Problem java.nio.file.ProviderNotFoundException: Provider "jar" not found 

### ISSUE THREAD

**Issue by nicoi15** [pf4j/pf4j#481]
Hi, quite new to pf4j, and I've been trying to load a plugin for a JavaFX application. It successfully works when running the app through IntelliJ, however, after the build and running the app with an executable I receive an error. 

Even though the logs show that the plugins were Resolved and Started, and the Path of the plugins is correct, it still fails to get the extensions.

````
[JavaFX Application Thread] INFO org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
[JavaFX Application Thread] INFO org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
[JavaFX Application Thread] INFO org.pf4j.DefaultPluginManager - PF4J version 3.5.0 in 'deployment' mode
[JavaFX Application Thread] INFO org.app.PluginService - PF4J Mode: deployment
[JavaFX Application Thread] INFO org.pf4j.AbstractPluginManager - Plugin 'screenshot@0.0.3' resolved
[JavaFX Application Thread] INFO org.pf4j.AbstractPluginManager - Plugin 'test-plugin@0.0.1' resolved
[JavaFX Application Thread] INFO org.pf4j.AbstractPluginManager - Start plugin 'screenshot@0.0.3'
[JavaFX Application Thread] INFO org.pf4j.AbstractPluginManager - Start plugin 'test-plugin@0.0.1'
[JavaFX Application Thread] INFO org.app.PluginService - PluginDirectory:
[JavaFX Application Thread] INFO org.app.PluginService -  D:\----\----\----\build\image-windows\----\bin\plugins\

[JavaFX Application Thread] INFO org.app.PluginService - New Extension Added: screenshot
[JavaFX Application Thread] INFO org.app.PluginService - New Extension Added: test-plugin
````

Here is the error

```` 
Caused by: java.nio.file.ProviderNotFoundException: Provider "jar" not found 
at java.base/java.nio.file.FileSystems.getFileSystem(Unknown Source)
at org.pf4j.util.FileUtils.getFileSystem(FileUtils.java:270)
at org.pf4j.util.FileUtils.getPath(FileUtils.java:235)
at org.pf4j.ServiceProviderExtensionFinder.collectExtensions(ServiceProviderExtensionFinder.java:126)
at org.pf4j.ServiceProviderExtensionFinder.collectExtensions(ServiceProviderExtensionFinder.java:118)
at org.pf4j.ServiceProviderExtensionFinder.readClasspathStorages(ServiceProviderExtensionFinder.java:69)
at org.pf4j.AbstractExtensionFinder.readStorages(AbstractExtensionFinder.java:301)
at org.pf4j.AbstractExtensionFinder.getEntries(AbstractExtensionFinder.java:309)
at org.pf4j.AbstractExtensionFinder.find(AbstractExtensionFinder.java:56)
at org.pf4j.DefaultExtensionFinder.find(DefaultExtensionFinder.java:45)
at org.pf4j.AbstractPluginManager.getExtensions(AbstractPluginManager.java:580)
at org.app.PluginService.lambda$bootExtensionPoints$0(PluginService.java:187)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
````

Below is the code

````
pluginManager = new DefaultPluginManager() {
      @Override
      protected PluginLoader createPluginLoader() {
          return new JarPluginLoader(this);
      }

      @Override
      protected PluginDescriptorFinder createPluginDescriptorFinder() {
          return new ManifestPluginDescriptorFinder();
      }

      protected ExtensionFinder createExtensionFinder() {
          DefaultExtensionFinder extensionFinder = (DefaultExtensionFinder) super.createExtensionFinder();
          extensionFinder.addServiceProviderExtensionFinder();

          return extensionFinder;
      }
  };

  log.info("PF4J Mode: " + pluginManager.getRuntimeMode());

  pluginManager.loadPlugins();
  pluginManager.startPlugins();
  log.info("PluginDirectory: ");
  log.info("\t" + System.getProperty("pf4j.pluginsDir") + "\n");

  updateManager = new UpdateManager(pluginManager);
  List<PluginWrapper> startedPlugins = pluginManager.getStartedPlugins();
    for (PluginWrapper plugin : startedPlugins) {
        String pluginId = plugin.getDescriptor().getPluginId();
        log.info("New Extension Added: " + pluginId);
  }

CompletableFuture<List<MainMenuExtensionPoint>> future1 = CompletableFuture.supplyAsync(() -> pluginManager.getExtensions(MainMenuExtensionPoint.class));
        try {
            List<MainMenuExtensionPoint> mainMenuExtensionPoint = future1.get();
            mainMenuExtensionPoints.setAll(mainMenuExtensionPoint);
            log.info(String.format("Loaded %d extensions for extension point %s", mainMenuExtensionPoint.size(),
                    MainMenuExtensionPoint.class.getName()));
        } catch (InterruptedException | ExecutionException e) {
            log.error("Error booting extensions", e);
        }
````

Any help or advice would be greatly appreciated.

**Comment by decebals** [comment]
I see that you use `ServiceProviderExtensionFinder`. Do you need this implementation (have some extensions that are defined via [Service Provider](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/ServiceLoader.html)) ?
What version of PF4J and Java are you using? What operating system (Linus, Windows, ..)?

**Comment by nicoi15** [comment]
The ```ServiceProviderExtensionFinder``` I think was just followed from the demo, but we are implementing for jars to have some extensions for the server and the client, and some jars may contain extensions only for the server.

version: '3.5.0'
OS: Windows 10
and Java 15

**Comment by decebals** [comment]
Please try to remove `createExtensionFinder` method from your code (when you create an instance of `DefaultPluginManager`) and run again the application. Also, try to use `JarPluginManager` instead of `DefaultPluginManager`, it's what you need in the end.

**Comment by nicoi15** [comment]
Awesome! It works like charm. Thank you! It works for both ```JarPluginManager``` and ```DefaultPluginManager``` with no ```createExtensionFinder```.
