### ISSUE TITLE
Cannot load plugin with in-memory Jar file using JIMFS

### ISSUE THREAD

**Issue by nicoi15** [pf4j/pf4j#482]
Hi, I'm trying to load a jar file that was stored as an in-memory using JIMFS.

When I try to pass the Path created from JIMFS to loadPlugin(jimfsPath) method, I get this error.

````
java.lang.UnsupportedOperationException
	at com.google.common.jimfs.JimfsPath.toFile(JimfsPath.java:387)
	at org.pf4j.ManifestPluginDescriptorFinder.readManifest(ManifestPluginDescriptorFinder.java:63)
	at org.pf4j.ManifestPluginDescriptorFinder.find(ManifestPluginDescriptorFinder.java:56)
	at org.pf4j.AbstractPluginManager.loadPluginFromPath(AbstractPluginManager.java:839)
	at org.pf4j.DefaultPluginManager.loadPluginFromPath(DefaultPluginManager.java:139)
	at org.pf4j.AbstractPluginManager.loadPlugin(AbstractPluginManager.java:201)
	at org.manticore.PluginService.installUIPlugin(PluginService.java:161)
	at org.manticore.PluginService.lambda$installPlugin$28(PluginService.java:639)
````
Does it support in-memory files or is there any workaround for this?

**Comment by decebals** [comment]
Please take a look on https://github.com/pf4j/pf4j/issues/476, try my recommendation and add your feedback.

**Comment by decebals** [comment]
@nicoi15 
After looking more closely to the exception stacktrace supplied by you I realized that path to file operation is not supported in JIMFS.
In [ManifestPluginDescriptorFinder](https://github.com/pf4j/pf4j/blob/master/pf4j/src/main/java/org/pf4j/ManifestPluginDescriptorFinder.java#L120) is used this operation so the result is clear.
I don't know if we can avoid this method in pf4j, so for the moment I don't see an immediate solution.

**Comment by decebals** [comment]
@nicoi15 
Please try using [file_to_path](https://github.com/pf4j/pf4j/pull/486). See #486 to see what is different.

**Comment by nicoi15** [comment]
@decebals 
Thank you. I will try it out.

**Comment by decebals** [comment]
@nicoi15 
Any news here?

**Comment by decebals** [comment]
@nicoi15 is this topic still of interest to you?

**Comment by decebals** [comment]
Close it due to lack of response. You can reopen it with a new comment.

**Comment by nicoi15** [comment]
Apologies for very late response. I think this is all good. Thanks.
