### ISSUE TITLE
LegacyExtensionFinder read META-INF/extensions.idx, cannot delete plugin jar file

### ISSUE THREAD

**Issue by my-fastcms** [pf4j/pf4j#484]
2022-01-17 00:25:45.303  INFO 20792 --- [           main] [o.s.b.w.embedded.tomcat.TomcatWebServer](url)  : Tomcat started on port(s): 9000 (http) with context path ''
2022-01-17 00:25:45.334  INFO 20792 --- [           main] com.fastcms.web.Fastcms                  : Started Fastcms in 9.988 seconds (JVM running for 10.775)
jar:file:/D:/IdeaProjects/fastcms/.dist/plugins/hello-world-plugin-0.0.1-SNAPSHOT.jar!/META-INF/extensions.idx
org.springframework.boot.loader.jar.ZipInflaterInputStream@403f137b
org.pf4j.PluginRuntimeException: java.nio.file.FileSystemException: D:\IdeaProjects\fastcms\.dist\.\plugins\hello-world-plugin-0.0.1-SNAPSHOT.jar: 另一个程序正在使用此文件，进程无法访
问。

        at org.pf4j.BasePluginRepository.deletePluginPath(BasePluginRepository.java:93)
        at org.pf4j.CompoundPluginRepository.deletePluginPath(CompoundPluginRepository.java:71)
        at org.pf4j.AbstractPluginManager.deletePlugin(AbstractPluginManager.java:345)
        at com.fastcms.plugin.FastcmsPluginManager.unInstallPlugin(FastcmsPluginManager.java:82)
        at com.fastcms.web.controller.admin.PluginController.unInstall(PluginController.java:111)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)

**Comment by decebals** [comment]
They are some (closed) [issues](https://github.com/pf4j/pf4j/issues?q=is%3Aissue+FileSystemException). Can you reproduce the problem in a simple manner (using [quickstart](https://pf4j.org/dev/quickstart.html) for example)? What PF4J version and OS are you using?

**Comment by techanjie** [comment]
user pf4j 3.6.0 version, OS is Windows
Read plugin.properties close stream, but read extensions.idx not close URL stream, PluginClassLoader is closed 

code here :
try {
                log.debug("Read '{}'", EXTENSIONS_RESOURCE);
                ClassLoader pluginClassLoader = plugin.getPluginClassLoader();
                try (InputStream resourceStream = **pluginClassLoader.getResourceAsStream(EXTENSIONS_RESOURCE)**) {
                    if (resourceStream == null) {
                        log.debug("Cannot find '{}'", EXTENSIONS_RESOURCE);
                    } else {
                        collectExtensions(resourceStream, bucket);
                    }
                }

                debugExtensions(bucket);

                result.put(pluginId, bucket);
            } catch (IOException e) {
                log.error(e.getMessage(), e);
            }

**Comment by techanjie** [comment]
And closing th resource stream does not work

**Comment by decebals** [comment]
As I said in my [previous](https://github.com/pf4j/pf4j/issues/484#issuecomment-1013911080)  comment, please replicate the problem (with a quickstart application or a junit test).

**Comment by decebals** [comment]
@techanjie 
Can you try using branch [file_to_path](https://github.com/pf4j/pf4j/tree/file_to_path) in your test?

**Comment by techanjie** [comment]
I'll try it sometime

**Comment by my-fastcms** [comment]
https://github.com/my-fastcms/fastcms.git
I use pf4j in this git project

**Comment by decebals** [comment]
> @techanjie Can you try using branch [file_to_path](https://github.com/pf4j/pf4j/tree/file_to_path) in your test?

@my-fastcms Any news here?
