### ISSUE TITLE
When I run the demo project, found it can not run

### ISSUE THREAD

**Issue by GEOHOTIOS** [pf4j/pf4j#501]
Folder Path: 
```
https://github.com/pf4j/pf4j/tree/master/demo
```
Operation: 
```
debug for app/src/main/java/org.pf4j.demo/Boot.java  Main method
```
Java version: 
```
JDK11 corretto-11.0.16
```
IDE: 
```
Intellij IDEA 2021.2.2(Ultimate Edition)
```
Debug Console Logs
```
H:\Users\Jobs\.jdks\corretto-11.0.16\bin\java.exe -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:58391,suspend=y,server=n -javaagent:H:\Users\Jobs\AppData\Local\JetBrains\IntelliJIdea2021.2\captureAgent\debugger-agent.jar -Dfile.encoding=UTF-8 -classpath "H:\Users\Jobs\Downloads\pf4j-master\pf4j-master\demo\app\target\classes;H:\Users\Jobs\.m2\repository\org\pf4j\pf4j\3.8.0-SNAPSHOT\pf4j-3.8.0-20220629.224438-1.jar;H:\Users\Jobs\.m2\repository\org\slf4j\slf4j-api\1.7.30\slf4j-api-1.7.30.jar;H:\Users\Jobs\.m2\repository\com\github\zafarkhaja\java-semver\0.9.0\java-semver-0.9.0.jar;H:\Users\Jobs\Downloads\pf4j-master\pf4j-master\demo\api\target\classes;H:\Users\Jobs\.m2\repository\org\apache\logging\log4j\log4j-api\2.17.1\log4j-api-2.17.1.jar;H:\Users\Jobs\.m2\repository\org\apache\logging\log4j\log4j-core\2.17.1\log4j-core-2.17.1.jar;H:\Users\Jobs\.m2\repository\org\apache\logging\log4j\log4j-slf4j-impl\2.17.1\log4j-slf4j-impl-2.17.1.jar;H:\Users\Jobs\.m2\repository\commons-lang\commons-lang\2.4\commons-lang-2.4.jar;H:\Program Files\JetBrains\IntelliJ IDEA 2021.2.2\lib\idea_rt.jar" org.pf4j.demo.Boot
Connected to the target VM, address: '127.0.0.1:58391', transport: 'socket'
2022-07-28 22:34:58,135 INFO org.pf4j.demo.Boot - ########################################
2022-07-28 22:34:58,138 INFO org.pf4j.demo.Boot -                PF4J-DEMO                
2022-07-28 22:34:58,138 INFO org.pf4j.demo.Boot - ########################################
2022-07-28 22:34:58,173 INFO org.pf4j.DefaultPluginStatusProvider - Enabled plugins: [welcome-plugin, hello-plugin]
2022-07-28 22:34:58,173 INFO org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
2022-07-28 22:34:58,179 INFO org.pf4j.DefaultPluginManager - PF4J version 3.8.0-SNAPSHOT in 'deployment' mode
2022-07-28 22:35:00,551 DEBUG org.pf4j.AbstractPluginManager - Lookup plugins in '[plugins]'
2022-07-28 22:35:00,558 DEBUG org.pf4j.AbstractPluginManager - Found 2 possible plugins: [plugins\plugin1, plugins\plugin2]
2022-07-28 22:35:00,558 DEBUG org.pf4j.AbstractPluginManager - Use 'org.pf4j.CompoundPluginDescriptorFinder@40317ba2' to find plugins descriptors
2022-07-28 22:35:00,558 DEBUG org.pf4j.AbstractPluginManager - Finding plugin descriptor for plugin 'plugins\plugin1'
2022-07-28 22:35:00,558 DEBUG org.pf4j.CompoundPluginDescriptorFinder - 'org.pf4j.PropertiesPluginDescriptorFinder@3c01cfa1' is applicable for plugin 'plugins\plugin1'
2022-07-28 22:35:00,559 DEBUG org.pf4j.PropertiesPluginDescriptorFinder - Lookup plugin descriptor in 'plugins\plugin1\plugin.properties'
2022-07-28 22:35:00,562 DEBUG org.pf4j.AbstractPluginManager - Found descriptor PluginDescriptor [pluginId=welcome-plugin, pluginClass=org.pf4j.demo.welcome.WelcomePlugin, version=0.0.1, provider=Decebal Suiu, dependencies=[], description=, requires=*, license=null]
2022-07-28 22:35:00,562 DEBUG org.pf4j.AbstractPluginManager - Class 'org.pf4j.demo.welcome.WelcomePlugin' for plugin 'plugins\plugin1'
2022-07-28 22:35:00,562 DEBUG org.pf4j.AbstractPluginManager - Loading plugin 'plugins\plugin1'
2022-07-28 22:35:00,563 DEBUG org.pf4j.CompoundPluginLoader - 'org.pf4j.JarPluginLoader@418c5a9c' is not applicable for plugin 'plugins\plugin1'
2022-07-28 22:35:00,563 DEBUG org.pf4j.CompoundPluginLoader - 'org.pf4j.DefaultPluginLoader@18e36d14' is applicable for plugin 'plugins\plugin1'
2022-07-28 22:35:00,565 DEBUG org.pf4j.AbstractPluginManager - Loaded plugin 'plugins\plugin1' with class loader 'org.pf4j.PluginClassLoader@352c1b98'
2022-07-28 22:35:00,565 DEBUG org.pf4j.AbstractPluginManager - Creating wrapper for plugin 'plugins\plugin1'
2022-07-28 22:35:00,566 DEBUG org.pf4j.AbstractPluginManager - Created wrapper 'PluginWrapper [descriptor=PluginDescriptor [pluginId=welcome-plugin, pluginClass=org.pf4j.demo.welcome.WelcomePlugin, version=0.0.1, provider=Decebal Suiu, dependencies=[], description=, requires=*, license=null], pluginPath=plugins\plugin1]' for plugin 'plugins\plugin1'
2022-07-28 22:35:00,566 DEBUG org.pf4j.AbstractPluginManager - Use 'org.pf4j.CompoundPluginDescriptorFinder@40317ba2' to find plugins descriptors
2022-07-28 22:35:00,566 DEBUG org.pf4j.AbstractPluginManager - Finding plugin descriptor for plugin 'plugins\plugin2'
2022-07-28 22:35:00,566 DEBUG org.pf4j.CompoundPluginDescriptorFinder - 'org.pf4j.PropertiesPluginDescriptorFinder@3c01cfa1' is applicable for plugin 'plugins\plugin2'
2022-07-28 22:35:00,566 DEBUG org.pf4j.PropertiesPluginDescriptorFinder - Lookup plugin descriptor in 'plugins\plugin2\plugin.properties'
2022-07-28 22:35:00,567 DEBUG org.pf4j.AbstractPluginManager - Found descriptor PluginDescriptor [pluginId=hello-plugin, pluginClass=org.pf4j.demo.hello.HelloPlugin, version=0.0.1, provider=Decebal Suiu, dependencies=[], description=, requires=*, license=null]
2022-07-28 22:35:00,567 DEBUG org.pf4j.AbstractPluginManager - Class 'org.pf4j.demo.hello.HelloPlugin' for plugin 'plugins\plugin2'
2022-07-28 22:35:00,567 DEBUG org.pf4j.AbstractPluginManager - Loading plugin 'plugins\plugin2'
2022-07-28 22:35:00,567 DEBUG org.pf4j.CompoundPluginLoader - 'org.pf4j.JarPluginLoader@418c5a9c' is not applicable for plugin 'plugins\plugin2'
2022-07-28 22:35:00,567 DEBUG org.pf4j.CompoundPluginLoader - 'org.pf4j.DefaultPluginLoader@18e36d14' is applicable for plugin 'plugins\plugin2'
2022-07-28 22:35:00,568 DEBUG org.pf4j.AbstractPluginManager - Loaded plugin 'plugins\plugin2' with class loader 'org.pf4j.PluginClassLoader@5965be2d'
2022-07-28 22:35:00,568 DEBUG org.pf4j.AbstractPluginManager - Creating wrapper for plugin 'plugins\plugin2'
2022-07-28 22:35:00,568 DEBUG org.pf4j.AbstractPluginManager - Created wrapper 'PluginWrapper [descriptor=PluginDescriptor [pluginId=hello-plugin, pluginClass=org.pf4j.demo.hello.HelloPlugin, version=0.0.1, provider=Decebal Suiu, dependencies=[], description=, requires=*, license=null], pluginPath=plugins\plugin2]' for plugin 'plugins\plugin2'
2022-07-28 22:35:00,569 DEBUG org.pf4j.DependencyResolver - Graph: 
   welcome-plugin -> []
   hello-plugin -> []
2022-07-28 22:35:00,569 DEBUG org.pf4j.DependencyResolver - Plugins order: [welcome-plugin, hello-plugin]
2022-07-28 22:35:00,570 INFO org.pf4j.AbstractPluginManager - Plugin 'welcome-plugin@0.0.1' resolved
2022-07-28 22:35:00,570 INFO org.pf4j.AbstractPluginManager - Plugin 'hello-plugin@0.0.1' resolved
2022-07-28 22:35:00,570 DEBUG org.pf4j.AbstractPluginManager - Plugin 'welcome-plugin@0.0.1' is not disabled
2022-07-28 22:35:00,570 INFO org.pf4j.AbstractPluginManager - Start plugin 'welcome-plugin@0.0.1'
2022-07-28 22:35:00,570 DEBUG org.pf4j.DefaultPluginFactory - Create instance for plugin 'org.pf4j.demo.welcome.WelcomePlugin'
2022-07-28 22:35:00,571 ERROR org.pf4j.DefaultPluginFactory - org.pf4j.demo.welcome.WelcomePlugin
java.lang.ClassNotFoundException: org.pf4j.demo.welcome.WelcomePlugin
	at org.pf4j.PluginClassLoader.loadClass(PluginClassLoader.java:144) ~[pf4j-3.8.0-20220629.224438-1.jar:3.8.0-SNAPSHOT]
	at org.pf4j.DefaultPluginFactory.create(DefaultPluginFactory.java:46) [pf4j-3.8.0-20220629.224438-1.jar:3.8.0-SNAPSHOT]
	at org.pf4j.PluginWrapper.getPlugin(PluginWrapper.java:81) [pf4j-3.8.0-20220629.224438-1.jar:3.8.0-SNAPSHOT]
	at org.pf4j.AbstractPluginManager.startPlugins(AbstractPluginManager.java:358) [pf4j-3.8.0-20220629.224438-1.jar:3.8.0-SNAPSHOT]
	at org.pf4j.demo.Boot.main(Boot.java:52) [classes/:?]
2022-07-28 22:35:00,583 ERROR org.pf4j.AbstractPluginManager - Unable to start plugin 'welcome-plugin@0.0.1'
java.lang.NullPointerException: null
	at org.pf4j.AbstractPluginManager.startPlugins(AbstractPluginManager.java:358) [pf4j-3.8.0-20220629.224438-1.jar:3.8.0-SNAPSHOT]
	at org.pf4j.demo.Boot.main(Boot.java:52) [classes/:?]
2022-07-28 22:35:00,583 INFO org.pf4j.AbstractPluginManager - Start plugin 'hello-plugin@0.0.1'
2022-07-28 22:35:00,583 DEBUG org.pf4j.DefaultPluginFactory - Create instance for plugin 'org.pf4j.demo.hello.HelloPlugin'
2022-07-28 22:35:00,583 ERROR org.pf4j.DefaultPluginFactory - org.pf4j.demo.hello.HelloPlugin
java.lang.ClassNotFoundException: org.pf4j.demo.hello.HelloPlugin
	at org.pf4j.PluginClassLoader.loadClass(PluginClassLoader.java:144) ~[pf4j-3.8.0-20220629.224438-1.jar:3.8.0-SNAPSHOT]
	at org.pf4j.DefaultPluginFactory.create(DefaultPluginFactory.java:46) [pf4j-3.8.0-20220629.224438-1.jar:3.8.0-SNAPSHOT]
	at org.pf4j.PluginWrapper.getPlugin(PluginWrapper.java:81) [pf4j-3.8.0-20220629.224438-1.jar:3.8.0-SNAPSHOT]
	at org.pf4j.AbstractPluginManager.startPlugins(AbstractPluginManager.java:358) [pf4j-3.8.0-20220629.224438-1.jar:3.8.0-SNAPSHOT]
	at org.pf4j.demo.Boot.main(Boot.java:52) [classes/:?]
2022-07-28 22:35:00,583 ERROR org.pf4j.AbstractPluginManager - Unable to start plugin 'hello-plugin@0.0.1'
java.lang.NullPointerException: null
	at org.pf4j.AbstractPluginManager.startPlugins(AbstractPluginManager.java:358) [pf4j-3.8.0-20220629.224438-1.jar:3.8.0-SNAPSHOT]
	at org.pf4j.demo.Boot.main(Boot.java:52) [classes/:?]
2022-07-28 22:35:00,584 DEBUG org.pf4j.AbstractExtensionFinder - Finding extensions of extension point 'org.pf4j.demo.api.Greeting'
2022-07-28 22:35:00,584 DEBUG org.pf4j.LegacyExtensionFinder - Reading extensions storages from classpath
2022-07-28 22:35:00,585 DEBUG org.pf4j.LegacyExtensionFinder - Read '/H:/Users/Jobs/Downloads/pf4j-master/pf4j-master/demo/app/target/classes/META-INF/extensions.idx'
2022-07-28 22:35:00,586 DEBUG org.pf4j.LegacyExtensionFinder - Read '/H:/Users/Jobs/Downloads/pf4j-master/pf4j-master/demo/api/target/classes/META-INF/extensions.idx'
2022-07-28 22:35:00,587 DEBUG org.pf4j.AbstractExtensionFinder - Found possible 1 extensions:
2022-07-28 22:35:00,587 DEBUG org.pf4j.AbstractExtensionFinder -    org.pf4j.demo.WhazzupGreeting
2022-07-28 22:35:00,587 DEBUG org.pf4j.LegacyExtensionFinder - Reading extensions storages from plugins
2022-07-28 22:35:00,587 DEBUG org.pf4j.LegacyExtensionFinder - Reading extensions storage from plugin 'welcome-plugin'
2022-07-28 22:35:00,587 DEBUG org.pf4j.LegacyExtensionFinder - Read 'META-INF/extensions.idx'
2022-07-28 22:35:00,588 DEBUG org.pf4j.AbstractExtensionFinder - Found possible 1 extensions:
2022-07-28 22:35:00,588 DEBUG org.pf4j.AbstractExtensionFinder -    org.pf4j.demo.WhazzupGreeting
2022-07-28 22:35:00,588 DEBUG org.pf4j.LegacyExtensionFinder - Reading extensions storage from plugin 'hello-plugin'
2022-07-28 22:35:00,588 DEBUG org.pf4j.LegacyExtensionFinder - Read 'META-INF/extensions.idx'
2022-07-28 22:35:00,588 DEBUG org.pf4j.AbstractExtensionFinder - Found possible 1 extensions:
2022-07-28 22:35:00,588 DEBUG org.pf4j.AbstractExtensionFinder -    org.pf4j.demo.WhazzupGreeting
2022-07-28 22:35:00,588 DEBUG org.pf4j.AbstractExtensionFinder - Finding extensions of extension point 'org.pf4j.demo.api.Greeting' for plugin 'null'
2022-07-28 22:35:00,588 DEBUG org.pf4j.AbstractExtensionFinder - Loading class 'org.pf4j.demo.WhazzupGreeting' using class loader 'jdk.internal.loader.ClassLoaders$AppClassLoader@71bc1ae4'
2022-07-28 22:35:00,589 DEBUG org.pf4j.AbstractExtensionFinder - Checking extension type 'org.pf4j.demo.WhazzupGreeting'
2022-07-28 22:35:00,592 DEBUG org.pf4j.AbstractExtensionFinder - Added extension 'org.pf4j.demo.WhazzupGreeting' with ordinal 0
2022-07-28 22:35:00,592 DEBUG org.pf4j.AbstractExtensionFinder - Found 1 extensions for extension point 'org.pf4j.demo.api.Greeting'
2022-07-28 22:35:00,592 DEBUG org.pf4j.AbstractExtensionFinder - Finding extensions of extension point 'org.pf4j.demo.api.Greeting' for plugin 'welcome-plugin'
2022-07-28 22:35:00,592 DEBUG org.pf4j.AbstractExtensionFinder - Finding extensions of extension point 'org.pf4j.demo.api.Greeting' for plugin 'hello-plugin'
2022-07-28 22:35:00,592 DEBUG org.pf4j.AbstractExtensionFinder - Found 1 extensions for extension point 'org.pf4j.demo.api.Greeting'
2022-07-28 22:35:00,592 DEBUG org.pf4j.DefaultExtensionFactory - Create instance for extension 'org.pf4j.demo.WhazzupGreeting'
2022-07-28 22:35:00,592 INFO org.pf4j.demo.Boot - Found 1 extensions for extension point 'org.pf4j.demo.api.Greeting'
2022-07-28 22:35:00,592 INFO org.pf4j.demo.Boot - >>> Whazzup
2022-07-28 22:35:00,592 INFO org.pf4j.demo.Boot - Extensions added by classpath:
2022-07-28 22:35:00,592 INFO org.pf4j.demo.Boot -    org.pf4j.demo.WhazzupGreeting
2022-07-28 22:35:00,593 INFO org.pf4j.demo.Boot - Extension classes by classpath:
2022-07-28 22:35:00,593 DEBUG org.pf4j.AbstractExtensionFinder - Finding extensions of extension point 'org.pf4j.demo.api.Greeting'
2022-07-28 22:35:00,593 DEBUG org.pf4j.AbstractExtensionFinder - Finding extensions of extension point 'org.pf4j.demo.api.Greeting' for plugin 'null'
2022-07-28 22:35:00,593 DEBUG org.pf4j.AbstractExtensionFinder - Loading class 'org.pf4j.demo.WhazzupGreeting' using class loader 'jdk.internal.loader.ClassLoaders$AppClassLoader@71bc1ae4'
2022-07-28 22:35:00,593 DEBUG org.pf4j.AbstractExtensionFinder - Checking extension type 'org.pf4j.demo.WhazzupGreeting'
2022-07-28 22:35:00,593 DEBUG org.pf4j.AbstractExtensionFinder - Added extension 'org.pf4j.demo.WhazzupGreeting' with ordinal 0
2022-07-28 22:35:00,593 DEBUG org.pf4j.AbstractExtensionFinder - Found 1 extensions for extension point 'org.pf4j.demo.api.Greeting'
2022-07-28 22:35:00,593 DEBUG org.pf4j.AbstractExtensionFinder - Finding extensions of extension point 'org.pf4j.demo.api.Greeting' for plugin 'welcome-plugin'
2022-07-28 22:35:00,593 DEBUG org.pf4j.AbstractExtensionFinder - Finding extensions of extension point 'org.pf4j.demo.api.Greeting' for plugin 'hello-plugin'
2022-07-28 22:35:00,593 DEBUG org.pf4j.AbstractExtensionFinder - Found 1 extensions for extension point 'org.pf4j.demo.api.Greeting'
2022-07-28 22:35:00,593 INFO org.pf4j.demo.Boot -    Class: org.pf4j.demo.WhazzupGreeting
2022-07-28 22:35:00,593 INFO org.pf4j.demo.Boot - Extensions instances added by classpath:
2022-07-28 22:35:00,593 DEBUG org.pf4j.AbstractExtensionFinder - Finding extensions from plugin 'null'
2022-07-28 22:35:00,593 DEBUG org.pf4j.AbstractExtensionFinder - Loading class 'org.pf4j.demo.WhazzupGreeting' using class loader 'jdk.internal.loader.ClassLoaders$AppClassLoader@71bc1ae4'
2022-07-28 22:35:00,593 DEBUG org.pf4j.AbstractExtensionFinder - Added extension 'org.pf4j.demo.WhazzupGreeting' with ordinal 0
2022-07-28 22:35:00,594 DEBUG org.pf4j.AbstractExtensionFinder - Found 1 extensions for plugin 'null'
2022-07-28 22:35:00,594 DEBUG org.pf4j.DefaultExtensionFactory - Create instance for extension 'org.pf4j.demo.WhazzupGreeting'
2022-07-28 22:35:00,594 INFO org.pf4j.demo.Boot -    org.pf4j.demo.WhazzupGreeting@4241e0f4
Disconnected from the target VM, address: '127.0.0.1:58391', transport: 'socket'

Process finished with exit code 0

```

**Comment by decebals** [comment]
I can't replicate the problem, probably something is configured incorrectly on your machine.
![image](https://user-images.githubusercontent.com/1248311/181917440-2cbad115-9ecb-4bb7-98db-0092375a6a2e.png)
