### ISSUE TITLE
Spring @ComponentScan not picking up plugin's Spring components

### ISSUE THREAD

**Issue by jchappelle** [pf4j/pf4j#93]
When I install my plugin as a zip file in the plugins folder, my spring configurations inside my plugin aren't being instantiated. I know you have a Spring project and I have looked at it, but it appears that it creates a separate ApplicationContext for each plugin. The reason this won't work for me is because my plugin has Autowired components like the main DataSource for the application. 

My ApplicationContext gets created via a ContextLoaderListener defined in the web.xml file. It looks like spring has done it's thing before the wicket Application.init method. I suppose I could create my ApplicationContext within my Application.init method instead of using a ContextLoaderListener but I'm not sure what other issues this might cause.

Have you faced this problem in the past? Can you provide me any guidance in how to make this work?

Thanks!

**Comment by decebals** [comment]
>  I know you have a Spring project and I have looked at it, but it appears that it creates a separate ApplicationContext for each plugin.

In [pf4j-spring](https://github.com/decebals/pf4j-spring) are two demos. 
The first demo exposes the PF4J's extensions as Spring 's beans.
The second demo is a more complex example where a plugin (see demo plugin2 - HelloPlugin) uses Spring Framework internally. In this situation, the `HelloPlugin extends SpringPlugin` and we override `createApplicationContext ` method and create a `Plugin's ApplicationContext`. For now it's a problem if you want to autowire components from the "global" ApplicationContext.
PF4J-Spring is a young and immature project and we can be improved in time. 
I don't use this module in my applications but I will see if I find an elegant solution for your problem.

**Comment by jchappelle** [comment]
Thank you. 

This one is kind of a blocker for me and I think my last main hurdle. I can't move forward with PF4J without this. It would take up too many resources for our plugin to have to recreate data sources and quartz schedulers and spring batch thread pools. It needs to be able to reuse those resources created by the main application.

I will also say this, for our application we are not going to be managing plugins while the application is running. So if we add or remove a plugin, the application will be stopped first. Using this approach maybe there is a way to somehow join classpaths from the plugins into the main application so that Spring can autowire plugin dependencies.

In case it helps, I created a special ContextLoaderListener that starts up a PluginManager before the Spring application. This didn't fix the problem but I thought I'd share just in case:

```
public class PF4JContextLoaderListener extends ContextLoaderListener
{
	private static final Logger log = LoggerFactory.getLogger(PF4JContextLoaderListener.class);

	private PluginManager pluginManager;

	@Override
	public void contextInitialized(ServletContextEvent event)
	{
		pluginManager = createPluginManager(event.getServletContext());
		if(pluginManager == null)
		{
			throw new RuntimeException("Plugin manager cannot be null");
		}

		log.debug("Created plugin manager {}", pluginManager);

		pluginManager.loadPlugins();
		pluginManager.startPlugins();

		super.contextInitialized(event);
	}

	@Override
	protected void customizeContext(ServletContext sc, ConfigurableWebApplicationContext wac)
	{
		wac.addBeanFactoryPostProcessor(new BeanFactoryPostProcessor()
		{
			@Override
			public void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory) throws BeansException
			{
				beanFactory.registerSingleton("pluginManager", pluginManager);
			}
		});
		super.customizeContext(sc, wac);
	}

	private PluginManager createPluginManager(ServletContext sc)
	{
		File pluginsDir = getPluginsDir(sc);
		log.debug("Plugins directory is {} ", pluginsDir);

		return new DefaultPluginManager(pluginsDir)
		{
			@Override
			protected ExtensionFinder createExtensionFinder()
			{
				return new LegacyExtensionFinder(this);
			}
		};
	}

	private File getPluginsDir(ServletContext sc)
	{
		String pluginsDir = System.getProperty("pf4j.pluginsDir");
		if(pluginsDir == null)
		{
			pluginsDir = sc.getInitParameter("pluginsDir");
		}
		if(pluginsDir == null)
		{
			String modeAsString = System.getProperty("pf4j.mode", RuntimeMode.DEPLOYMENT.toString());
			RuntimeMode runtimeMode = RuntimeMode.byName(modeAsString);
			if(RuntimeMode.DEVELOPMENT.equals(runtimeMode))
			{
				pluginsDir = DefaultPluginManager.DEVELOPMENT_PLUGINS_DIRECTORY;
			}
			else
			{
				pluginsDir = DefaultPluginManager.DEFAULT_PLUGINS_DIRECTORY;
			}
		}
		return new File(pluginsDir);
	}
}
```

**Comment by decebals** [comment]
> I can't move forward with PF4J without this.

I am sure that we find an elegant solution.

I have some ideas to move forward your project.
Spring lets you define multiple contexts in a parent-child hierarchy. The `applicationContext.xml` defines the beans for the "core application context". The `pluginContext.xml` (or whatever else you call it) defines the beans for one plugin's app context.  There can be many of these in a (web)app, one per (Spring) plugin.
From what I know (maybe I am wrong), Beans in `pluginContext.xml` can reference beans in `applicationContext.xml`, but not vice versa.
I my mind, `applicationContext.xml` is generally used to contain beans that are shared between all plugins in a (web)app.
If I define a [spring plugin](https://github.com/decebals/pf4j-spring/blob/master/demo/plugins/plugin2/src/main/java/ro/fortsoft/pf4j/demo/hello/HelloPlugin.java) (`MySpringPlugin extends SpringPlugin`) I must implement `SpringPlugin.createApplicationContext` method. 
So, my code can looks like:
```java
AnnotationConfigApplicationContext pluginContext = new AnnotationConfigApplicationContext();
pluginContext .setParent(applicationContext); <-- HERE
...
```

Now it's time to `extract` the parent application context. In this case I can use `pluginWrapper. getPluginManager()`.
So, my code can looks like:
```java
SpringPluginManager pluginManager = (SpringPluginManager) pluginWrapper. getPluginManager();
ApplicationContext applicationContext = pluginManager.getApplicationContext();
...
```

Sure, above I described a possible solution in theory and I am not sure that it works.

**Comment by jchappelle** [comment]
> From what I know (maybe I am wrong), Beans in pluginContext.xml can reference beans in applicationContext.xml, but not vice versa.
> I my mind, applicationContext.xml is generally used to contain beans that are shared between all plugins in a (web)app.

I agree completely. I don't think we have anything in our main app that would require an implementation provided by our plugin's application context. If we do then that is a design problem that needs to be addressed. If this happens it's really a hidden dependency. 

I like your idea. I'll see if I can play with this and make it work.

**Comment by jchappelle** [comment]
I know this probably isn't enough information but I got this error after implementing that. 

It sounds like from the error message that the JVM doesn't like the fact that I have a method signature "createApplicationContext" that returns a org.springframework.context.ApplicationContext when there are two instances of that class, once instance in the plugin class loader and one instance in the main class loader. I don't have much experience with class loaders so I thought I'd share and see if you've ever dealt with this.

I will create a small separate project so I can isolate the problem and share it with you. For now here's the summary of what I got in case you're curious.

```
Caused by: java.lang.LinkageError: loader constraint violation: when resolving overridden method "com.mycompany.fraud.wicket.plugin.FraudPlugin.createApplicationContext()Lorg/springframework/context/ApplicationContext;" the class loader (instance of ro/fortsoft/pf4j/PluginClassLoader) of the current class, com/mycompany/fraud/wicket/plugin/FraudPlugin, and its superclass loader (instance of org/eclipse/jetty/webapp/WebAppClassLoader), have different Class objects for the type org/springframework/context/ApplicationContext used in the signature
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.getConstructor(Unknown Source)
	at ro.fortsoft.pf4j.DefaultPluginFactory.create(DefaultPluginFactory.java:63)
	at ro.fortsoft.pf4j.PluginWrapper.getPlugin(PluginWrapper.java:75)
	at ro.fortsoft.pf4j.DefaultPluginManager.startPlugins(DefaultPluginManager.java:231)
	at com.mycompany.wicket.spring.WebAppConfig.pluginManager(WebAppConfig.java:54)
	at com.mycompany.wicket.spring.WebAppConfig$$EnhancerBySpringCGLIB$$59f425ec.CGLIB$pluginManager$0(<generated>)
	at com.mycompany.wicket.spring.WebAppConfig$$EnhancerBySpringCGLIB$$59f425ec$$FastClassBySpringCGLIB$$1860aada.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:309)
	at com.mycompany.wicket.spring.WebAppConfig$$EnhancerBySpringCGLIB$$59f425ec.pluginManager(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 71 more

```
```
public class FraudPlugin extends SpringPlugin
{
	private static final Logger log = LoggerFactory.getLogger(FraudPlugin.class);
	
	private final ApplicationContext parentApplicationContext;
	
	public FraudPlugin(PluginWrapper wrapper)
	{
		super(wrapper);
		
		log.info("Constructing Fraud Plugin (" + wrapper.getPluginId() + ")");

		PluginManager manager = wrapper.getPluginManager();
		if(manager instanceof SpringPluginManager)
		{
			parentApplicationContext = ((SpringPluginManager)manager).getApplicationContext();
		}
		else
		{
			parentApplicationContext = null;
			log.warn("PluginManager is not a " + SpringPluginManager.class + ". Instead it is a " + manager.getClass());
		}
	}

	@Override
	protected ApplicationContext createApplicationContext()
	{
		AnnotationConfigApplicationContext pluginContext = new AnnotationConfigApplicationContext(FraudConfig.class);
		if(parentApplicationContext == null)
		{
			log.warn("A parent ApplicationContext was not set. Your plugin will not be able to autowire beans from the main application.");
		}
		else
		{
			pluginContext.setParent(parentApplicationContext);
		}
		return pluginContext;
	}
}
```

```
public class SpringPluginManager extends DefaultPluginManager implements ApplicationContextAware
{
	private ApplicationContext applicationContext;

	@Override
	public void setApplicationContext(ApplicationContext applicationContext) throws BeansException
	{
		this.applicationContext = applicationContext;
	}

	public ApplicationContext getApplicationContext()
	{
		return applicationContext;
	}
}
```
Beans inside my main application context:
```
	@Bean
	public ExtensionProvider extensionProvider()
	{
		return new PluginManagerExtensionProvider(pluginManager());
	}

	@Bean
	public PluginManager pluginManager()
	{
		PluginManager result = new SpringPluginManager()
		{
			@Override
			protected ExtensionFactory createExtensionFactory()
			{
				return new SpringExtensionFactory(this);
			}

			@Override
			protected ExtensionFinder createExtensionFinder()
			{
				return new LegacyExtensionFinder(this);
			}
		};
		result.loadPlugins();
		result.startPlugins();
		return result;
	}

	@Bean
	public static ExtensionsInjector extensionsInjector()
	{
		return new ExtensionsInjector();
	}
```

**Comment by jchappelle** [comment]
Ok I've reproduced it in a small sample project. Please disregard the name of the project having to do with springbean. I already had this setup for spring stuff(testing a separate issue) and I didn't want to recreate a whole new project.

To run the webapp, just navigate your command line to the pf4j-springbean-parent directory and execute run-demo.bat. It's pretty much the same as yours except it runs the webapp instead of a jar file.

You should see the following error:

```
Caused by: java.lang.LinkageError: loader constraint violation: when resolving overridden method "com.mycompany.pf4j.springbean.plugin.MySpringPlugin.createApplicationContext()Lorg/springframework/context/ApplicationContext;" the class loader (instance of ro/fortsoft/pf4j/PluginClassLoader) of the current class, com/mycompany/pf4j/springbean/plugin/MySpringPlugin, and its superclass loader (instance of org/eclipse/jetty/webapp/WebAppClassLoader), have different Class objects for the type org/springframework/context/ApplicationContext used in the signature
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.getConstructor(Unknown Source)
	at ro.fortsoft.pf4j.DefaultPluginFactory.create(DefaultPluginFactory.java:63)
	at ro.fortsoft.pf4j.PluginWrapper.getPlugin(PluginWrapper.java:75)
	at ro.fortsoft.pf4j.DefaultPluginManager.startPlugins(DefaultPluginManager.java:231)
	at com.mycompany.pf4j.springbean.webapp.SpringConfig.pluginManager(SpringConfig.java:38)
	at com.mycompany.pf4j.springbean.webapp.SpringConfig$$EnhancerBySpringCGLIB$$e7794dda.CGLIB$pluginManager$0(<generated>)
	at com.mycompany.pf4j.springbean.webapp.SpringConfig$$EnhancerBySpringCGLIB$$e7794dda$$FastClassBySpringCGLIB$$64719a43.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:309)
	at com.mycompany.pf4j.springbean.webapp.SpringConfig$$EnhancerBySpringCGLIB$$e7794dda.pluginManager(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 71 more

```

[pf4j-springbean-parent.zip](https://github.com/decebals/pf4j/files/143893/pf4j-springbean-parent.zip)

**Comment by jchappelle** [comment]
Ok I found out what was going on there. I needed to change the scope on my spring dependencies to "provided" since the containing app already had those and it was clashing. Got the idea from here: http://stackoverflow.com/questions/3998904/jboss5-class-loader-problem-with-spring-and-hibernate-trying-to-parse-applicatio

Now I get a more meaningful error:
```
java.lang.IllegalStateException: Cannot load configuration class: com.mycompany.pf4j.springbean.plugin.SpringPluginConfig
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:395)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(ConfigurationClassPostProcessor.java:259)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:265)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:126)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:606)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:462)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
	at com.mycompany.pf4j.springbean.plugin.MySpringPlugin.createApplicationContext(MySpringPlugin.java:39)
	at ro.fortsoft.pf4j.spring.SpringPlugin.getApplicationContext(SpringPlugin.java:36)
	at ro.fortsoft.pf4j.spring.SpringExtensionFactory.create(SpringExtensionFactory.java:55)
	at ro.fortsoft.pf4j.spring.ExtensionsInjector.postProcessBeanFactory(ExtensionsInjector.java:64)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:265)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:177)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:606)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:462)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
	at org.eclipse.jetty.maven.plugin.JettyWebAppContext.startWebapp(JettyWebAppContext.java:296)

```
Here's the updated project
[pf4j-springbean-parent.zip](https://github.com/decebals/pf4j/files/143905/pf4j-springbean-parent.zip)

**Comment by jchappelle** [comment]
I was able to get the class to resolve by calling setClassLoader like this:
```
	@Override
	protected ApplicationContext createApplicationContext()
	{
		AnnotationConfigApplicationContext pluginContext = new AnnotationConfigApplicationContext();
		pluginContext.setClassLoader(getWrapper().getPluginClassLoader());
		if(parentApplicationContext == null)
		{
			log.warn("A parent ApplicationContext was not set. Your plugin will not be able to autowire beans from the main application.");
		}
		else
		{
			pluginContext.setParent(parentApplicationContext);
		}
		pluginContext.register(SpringPluginConfig.class);
		pluginContext.refresh();
		return pluginContext;
	}

```

Now I get this error. I think we're closer, I even see in the logs where it's constructing bean 'myService'. But no success yet.

`org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'myService' is defined`

**Comment by jchappelle** [comment]
I made some progress. But I'm going to bed for the night. Sorry I added so many comments. I kept thinking I was about to stop but I kept getting farther. Here is my latest code. I'm getting:
```
[WARNING] Failed startup of context o.e.j.m.p.JettyWebAppContext@131fcb6f{/,file:/C:/eclipse-workspaces/redi/pf4j-springbean-parent/pf4j-springbean-webapp/src/main/webapp/,STARTING}{file:/C:/eclipse-workspaces/redi/pf4j-springbean-parent/pf4j-springbean-webapp/src/main/webapp/}
java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: Root WebApplicationContext: startup date [Tue Feb 23 23:11:42 CST 2016]; root of context hierarchy
	at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:344)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:333)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:773)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
	at com.mycompany.pf4j.springbean.plugin.MySpringPlugin.createApplicationContext(MySpringPlugin.java:51)
	at ro.fortsoft.pf4j.spring.SpringPlugin.getApplicationContext(SpringPlugin.java:36)
	at ro.fortsoft.pf4j.spring.SpringExtensionFactory.create(SpringExtensionFactory.java:55)
	at ro.fortsoft.pf4j.spring.ExtensionsInjector.postProcessBeanFactory(ExtensionsInjector.java:64)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:265)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:177)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:606)

```
[pf4j-springbean-parent.zip](https://github.com/decebals/pf4j/files/143979/pf4j-springbean-parent.zip)

**Comment by jchappelle** [comment]
I got it to work but the wicket integration is ugly.

My last problem was a NoSuchBeanDefinitionException. It occurred to me that my MyServiceMessagePanel was using @SpringBean for injecting spring services. This will try to find my bean from the parent ApplicationContext which does not see child context beans. So in my plugin panel I did the following:
```
	public MyServiceMessagePanel(String id)
	{
		super(id);
		add(new Label("message", MySpringPlugin.get().getApplicationContext().getBean(MyService.class).getMessage()));
	}

```

You can see why I say the wicket integration is ugly. It would be great if I could customize the SpringComponentInjector so that it could route me to the correct application context based on the plugin that the panel class is in. I'm thinking of using PluginManager.whichPlugin in a custom SpringComponentInjector. If you have a better idea please let me know.

Here's my latest code:
[pf4j-springbean-parent.zip](https://github.com/decebals/pf4j/files/144821/pf4j-springbean-parent.zip)

**Comment by jchappelle** [comment]
I have posted questions on the wicket forum and stackoverflow for help on this.

http://stackoverflow.com/questions/35608610/springbean-support-for-bean-in-child-applicationcontext

http://apache-wicket.1842946.n4.nabble.com/SpringBean-support-for-bean-in-child-ApplicationContext-td4673719.html

**Comment by decebals** [comment]
> To run the webapp, just navigate your command line to the pf4j-springbean-parent directory and execute run-demo.bat

I took a look at your demo application and I want to give a hint about how I work with PF4J in my projects.
I am a linux guy but it's not a problem for me to convert run-demo.bat to run-demo.sh 
My project structure is similar with the structure of pf4j demo. I put `app` and `api` modules in two folders and all my plugin modules are grouped in a `plugins` folder.
So, the layout of the application is:
```
- api
- app
- plugins
   - plugin_1
   - plugin_2
   ...
   - plugin_n
```

I use above layout because I want to run and debug my application from my IDE and not from command line. All I must to do is to run my application with `-Dpf4j.mode=development` and to have a `plugin.properties` file in each plugin folder. That is all.

I converted you application to my layout with some minor modification:
- create a `plugins` folder (`mkdir plugins`)
- move to `plugins` folder (`mv plugins`)
- create a `symbolic link` to plugin module (`ln -s ../pf4j-springbean-plugin .`)
- add `Start.java` in my app module
- create a plugin.properties in pf4j-springbean-plugin folder

Now I can run/debug my application (via Start class) from my favorite IDE (IDEA in my case) using `-Dpf4j.mode=development`  with `app` marked as working directory.

**Comment by jchappelle** [comment]
cool. I'll do that in my future posts.

**Comment by decebals** [comment]
> You can see why I say the wicket integration is ugly.

Yes I know. I don't know if I can help.

**Comment by jchappelle** [comment]
I may just have to go a different route then. I might still use PF4J, or maybe just ServiceLoader. I can deploy my plugin/module as an uber jar using the [maven shade plugin](https://maven.apache.org/plugins/maven-shade-plugin/). I'll just have to make sure no dependencies clash. I think we can do that since we are the developers of the main app and the plugins.

This way everyone lives in the same classpath in a nice peaceful world instead of the evil world of separate ClassLoaders :-)

I do like your project and now that I've learned a lot about it I may offer some pull requests from time to time if that's alright.

Thanks for all your help!

**Comment by decebals** [comment]
For people that read this page I want to share http://stackoverflow.com/questions/7746633/declaring-spring-bean-in-parent-context-vs-child-context. It's a good explanation (see the accepted answer) of parent-child context relation in Spring Framework.

**Comment by jchappelle** [comment]
I will add to that.

The reason I wasn't able to simply add my plugin beans to the parent context was for two reasons:

1. The plugin has a separate class loader. You will get a ClassNotFoundException when you try to register your config class to the parent.
2. Even if it did work, it would require you call refresh() after adding the beans, which would cause the ApplicationContext to destroy all existing beans and reload them. In a large application this isn't a good idea. Each plugin would cause this behavior.

Loading a separate ApplicationContext would have worked fine from PF4J's standpoint. Except the Wicket Spring integration doesn't allow for multiple ApplicationContexts.

**Comment by decebals** [comment]
I don't know if it help but in a previous version was an utility class [CompundClassLoader](https://github.com/decebals/pf4j/blob/release-0.11.0/pf4j/src/main/java/ro/fortsoft/pf4j/util/CompoundClassLoader.java`) and practically you can see that class loader like an UberClassLoader (contains all PluginClassLoaders), Maybe using this class in your PluginManager you can have a global ApplicationContext, of course you must add set the class loader with `applicationContext.setClassLoader(pluginManager.getAllPluginsClassLoader())`.
Your global application context is dynamic and it contains the parent/core application context and the plugins application context (maybe something similar with `classpath:pluginContext.xml`).
In your wicket application you must use the global application context.
It's only an idea and I don't know if it's OK.

**Comment by jchappelle** [comment]
That would still leave problem #2. The application context would have to be completely reloaded with each plugin.

I was just thinking of implementing a solution like this. Having an IComponentInstantiationListenerFilter that would delegate to the appropriate SpringComponentInjector. Each injector would have a reference to the plugin's application context like so:

```
public class ComponentInstantiationListenerFilter implements IComponentInstantiationListener
{
	private final IComponentInstantiationListener delegate;
	
	public ComponentInstantiationListenerFilter(IComponentInstantiationListener delegate)
	{
		this.delegate = delegate;
	}
	
	public void onInstantiation(Component component)
	{
		if(matches(component))
		{
			delegate.onInstantiation(component);
		}
	}
	
	private boolean matches(Component component)
	{
		return component.getClass().getName().contains("plugin");//Maybe a better way?
	}
}
```
In plugin init method
`getComponentInstantiationListeners().add(new ComponentInstantiationListenerFilter(new SpringComponentInjector(wicketApplication, pluginContext)));
`

The only problem with this is that SpringComponentInjector uses a MetaDataKey to cache the ApplicationContext. So I would have to somehow create a MetaDataKey for each plugin and pass it to a custom SpringComponentInjector.

It's just not a clean solution and there are too many things that could go wrong in production.

If you think of any other ideas please let me know. I'm open to them. However, I gotta keep moving on the project so I'm going with my uber jar idea for now. The nice thing about that is that if we ever do find a solution it shouldn't be hard for me to switch back over.

**Comment by jchappelle** [comment]
One of the wicket developers gave me an answer. It's pretty much what I was talking about with the IComponentInstantiationListener. This answer gives me hope that it can be done. I may continue toying with this when I have time.

http://stackoverflow.com/questions/35608610/springbean-support-for-bean-in-child-applicationcontext/35623736#35623736

**Comment by decebals** [comment]
I don't know if we must close this issue and eventually open other with a more clear description.

**Comment by shiyeling** [comment]
I was trying to do similar thing in spring boot app, spring seems not able to detect the annotation in the plugin jar.
The below post helped me out.
https://stackoverflow.com/questions/41148353/dynamically-add-jars-to-springboot-at-runtime/41148674#41148674

Most likely this issue has something to do with the classpath setup.

**Comment by decebals** [comment]
Please open an issue in pf4j-spring project if you consider.
